// Code generated by data_gen.go. DO NOT EDIT.

package lunit

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type TempUnitEnum uint8

const (
	TempUnitEnumFahrenheit TempUnitEnum = 0
	TempUnitEnumCelsius TempUnitEnum = 1
	TempUnitEnumKelvin TempUnitEnum = 2
)



