// Code generated by data_gen.go. DO NOT EDIT.

package lvl

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type MoveModeEnum uint8

const (
	MoveModeEnumUp MoveModeEnum = 0
	MoveModeEnumDown MoveModeEnum = 1
)

type StepModeEnum uint8

const (
	StepModeEnumUp StepModeEnum = 0
	StepModeEnumDown StepModeEnum = 1
)

type OptionsBitmap uint8

const (
	OptionsBitmapExecuteIfOff OptionsBitmap = 0x1
	OptionsBitmapCoupleColorTempToLevel OptionsBitmap = 0x2
)



