// Code generated by data_gen.go. DO NOT EDIT.

package conc

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type LevelValueEnum uint8

const (
	LevelValueEnumUnknown LevelValueEnum = 0
	LevelValueEnumLow LevelValueEnum = 1
	LevelValueEnumMedium LevelValueEnum = 2
	LevelValueEnumHigh LevelValueEnum = 3
	LevelValueEnumCritical LevelValueEnum = 4
)

type MeasurementMediumEnum uint8

const (
	MeasurementMediumEnumAir MeasurementMediumEnum = 0
	MeasurementMediumEnumWater MeasurementMediumEnum = 1
	MeasurementMediumEnumSoil MeasurementMediumEnum = 2
)

type MeasurementUnitEnum uint8

const (
	MeasurementUnitEnumPPM MeasurementUnitEnum = 0
	MeasurementUnitEnumPPB MeasurementUnitEnum = 1
	MeasurementUnitEnumPPT MeasurementUnitEnum = 2
	MeasurementUnitEnumMGM3 MeasurementUnitEnum = 3
	MeasurementUnitEnumUGM3 MeasurementUnitEnum = 4
	MeasurementUnitEnumNGM3 MeasurementUnitEnum = 5
	MeasurementUnitEnumPM3 MeasurementUnitEnum = 6
	MeasurementUnitEnumBQM3 MeasurementUnitEnum = 7
)



