// Code generated by data_gen.go. DO NOT EDIT.

package otap

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ApplyUpdateActionEnum uint8

const (
	ApplyUpdateActionEnumProceed ApplyUpdateActionEnum = 0
	ApplyUpdateActionEnumAwaitNextAction ApplyUpdateActionEnum = 1
	ApplyUpdateActionEnumDiscontinue ApplyUpdateActionEnum = 2
)

type DownloadProtocolEnum uint8

const (
	DownloadProtocolEnumBDXSynchronous DownloadProtocolEnum = 0
	DownloadProtocolEnumBDXAsynchronous DownloadProtocolEnum = 1
	DownloadProtocolEnumHTTPS DownloadProtocolEnum = 2
	DownloadProtocolEnumVendorSpecific DownloadProtocolEnum = 3
)

type StatusEnum uint8

const (
	StatusEnumUpdateAvailable StatusEnum = 0
	StatusEnumBusy StatusEnum = 1
	StatusEnumNotAvailable StatusEnum = 2
	StatusEnumDownloadProtocolNotSupported StatusEnum = 3
)



