// Code generated by data_gen.go. DO NOT EDIT.

package brbinfo

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ColorEnum uint8

const (
	ColorEnumBlack ColorEnum = 0
	ColorEnumNavy ColorEnum = 1
	ColorEnumGreen ColorEnum = 2
	ColorEnumTeal ColorEnum = 3
	ColorEnumMaroon ColorEnum = 4
	ColorEnumPurple ColorEnum = 5
	ColorEnumOlive ColorEnum = 6
	ColorEnumGray ColorEnum = 7
	ColorEnumBlue ColorEnum = 8
	ColorEnumLime ColorEnum = 9
	ColorEnumAqua ColorEnum = 10
	ColorEnumRed ColorEnum = 11
	ColorEnumFuchsia ColorEnum = 12
	ColorEnumYellow ColorEnum = 13
	ColorEnumWhite ColorEnum = 14
	ColorEnumNickel ColorEnum = 15
	ColorEnumChrome ColorEnum = 16
	ColorEnumBrass ColorEnum = 17
	ColorEnumCopper ColorEnum = 18
	ColorEnumSilver ColorEnum = 19
	ColorEnumGold ColorEnum = 20
)

type ProductFinishEnum uint8

const (
	ProductFinishEnumOther ProductFinishEnum = 0
	ProductFinishEnumMatte ProductFinishEnum = 1
	ProductFinishEnumSatin ProductFinishEnum = 2
	ProductFinishEnumPolished ProductFinishEnum = 3
	ProductFinishEnumRugged ProductFinishEnum = 4
	ProductFinishEnumFabric ProductFinishEnum = 5
)



