// Code generated by data_gen.go. DO NOT EDIT.

package dgsw

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()







type ThreadMetrics struct {
	ID uint64 // Tag 0
	Name *string // Tag 1
	StackFreeCurrent *uint32 // Tag 2
	StackFreeMinimum *uint32 // Tag 3
	StackSize *uint32 // Tag 4
}

func (s *ThreadMetrics) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.ID)
    
	// Field: Name Tag: 1
    if s.Name != nil {
        st[tlv.ContextTag(1)] = (*s.Name)
    }
	// Field: StackFreeCurrent Tag: 2
    if s.StackFreeCurrent != nil {
        st[tlv.ContextTag(2)] = uint64(*s.StackFreeCurrent)
    }
	// Field: StackFreeMinimum Tag: 3
    if s.StackFreeMinimum != nil {
        st[tlv.ContextTag(3)] = uint64(*s.StackFreeMinimum)
    }
	// Field: StackSize Tag: 4
    if s.StackSize != nil {
        st[tlv.ContextTag(4)] = uint64(*s.StackSize)
    }
	return st
}

func (s *ThreadMetrics) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint64(v)
s.ID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.StackFreeCurrent = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.StackFreeMinimum = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.StackSize = &casted
}
        
        
	}

    return nil
}

