// Code generated by data_gen.go. DO NOT EDIT.

package boolcfg

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type AlarmModeBitmap uint8

const (
	AlarmModeBitmapVisual AlarmModeBitmap = 0x1
	AlarmModeBitmapAudible AlarmModeBitmap = 0x2
)

type SensorFaultBitmap uint8

const (
	SensorFaultBitmapGeneralFault SensorFaultBitmap = 0x1
)



