// Code generated by data_gen.go. DO NOT EDIT.

package occ

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type OccupancySensorTypeEnum uint8

const (
	OccupancySensorTypeEnumPIR OccupancySensorTypeEnum = 0
	OccupancySensorTypeEnumUltrasonic OccupancySensorTypeEnum = 1
	OccupancySensorTypeEnumPIRAndUltrasonic OccupancySensorTypeEnum = 2
	OccupancySensorTypeEnumPhysicalContact OccupancySensorTypeEnum = 3
)

type OccupancyBitmap uint8

const (
	OccupancyBitmapOccupied OccupancyBitmap = 0x1
)

type OccupancySensorTypeBitmap uint8

const (
	OccupancySensorTypeBitmapPIR OccupancySensorTypeBitmap = 0x1
	OccupancySensorTypeBitmapUltrasonic OccupancySensorTypeBitmap = 0x2
	OccupancySensorTypeBitmapPhysicalContact OccupancySensorTypeBitmap = 0x4
)



type HoldTimeLimits struct {
	HoldTimeMin uint16 // Tag 0
	HoldTimeMax uint16 // Tag 1
	HoldTimeDefault uint16 // Tag 2
}

func (s *HoldTimeLimits) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: HoldTimeMin Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.HoldTimeMin)
    
	// Field: HoldTimeMax Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.HoldTimeMax)
    
	// Field: HoldTimeDefault Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.HoldTimeDefault)
    
	return st
}

func (s *HoldTimeLimits) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.HoldTimeMin = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.HoldTimeMax = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.HoldTimeDefault = casted
}
        
        
	}

    return nil
}

