// Code generated by data_gen.go. DO NOT EDIT.

package ill

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type LightSensorTypeEnum uint8

const (
	LightSensorTypeEnumPhotodiode LightSensorTypeEnum = 0
	LightSensorTypeEnumCMOS LightSensorTypeEnum = 1
)



