// Code generated by data_gen.go. DO NOT EDIT.

package cc

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ColorLoopActionEnum uint8

const (
	ColorLoopActionEnumDeactivate ColorLoopActionEnum = 0
	ColorLoopActionEnumActivateFromColorLoopStartEnhancedHue ColorLoopActionEnum = 1
	ColorLoopActionEnumActivateFromEnhancedCurrentHue ColorLoopActionEnum = 2
)

type ColorLoopDirectionEnum uint8

const (
	ColorLoopDirectionEnumDecrement ColorLoopDirectionEnum = 0
	ColorLoopDirectionEnumIncrement ColorLoopDirectionEnum = 1
)

type ColorModeEnum uint8

const (
	ColorModeEnumCurrentHueAndCurrentSaturation ColorModeEnum = 0
	ColorModeEnumCurrentXAndCurrentY ColorModeEnum = 1
	ColorModeEnumColorTemperatureMireds ColorModeEnum = 2
)

type DirectionEnum uint8

const (
	DirectionEnumShortest DirectionEnum = 0
	DirectionEnumLongest DirectionEnum = 1
	DirectionEnumUp DirectionEnum = 2
	DirectionEnumDown DirectionEnum = 3
)

type DriftCompensationEnum uint8

const (
	DriftCompensationEnumNone DriftCompensationEnum = 0
	DriftCompensationEnumOtherOrUnknown DriftCompensationEnum = 1
	DriftCompensationEnumTemperatureMonitoring DriftCompensationEnum = 2
	DriftCompensationEnumOpticalLuminanceMonitoringAndFeedback DriftCompensationEnum = 3
	DriftCompensationEnumOpticalColorMonitoringAndFeedback DriftCompensationEnum = 4
)

type EnhancedColorModeEnum uint8

const (
	EnhancedColorModeEnumCurrentHueAndCurrentSaturation EnhancedColorModeEnum = 0
	EnhancedColorModeEnumCurrentXAndCurrentY EnhancedColorModeEnum = 1
	EnhancedColorModeEnumColorTemperatureMireds EnhancedColorModeEnum = 2
	EnhancedColorModeEnumEnhancedCurrentHueAndCurrentSaturation EnhancedColorModeEnum = 3
)

type MoveModeEnum uint8

const (
	MoveModeEnumStop MoveModeEnum = 0
	MoveModeEnumUp MoveModeEnum = 1
	MoveModeEnumDown MoveModeEnum = 3
)

type StepModeEnum uint8

const (
	StepModeEnumUp StepModeEnum = 1
	StepModeEnumDown StepModeEnum = 3
)

type ColorCapabilitiesBitmap uint8

const (
	ColorCapabilitiesBitmapHueSaturation ColorCapabilitiesBitmap = 0x1
	ColorCapabilitiesBitmapEnhancedHue ColorCapabilitiesBitmap = 0x2
	ColorCapabilitiesBitmapColorLoop ColorCapabilitiesBitmap = 0x4
	ColorCapabilitiesBitmapXY ColorCapabilitiesBitmap = 0x8
	ColorCapabilitiesBitmapColorTemperature ColorCapabilitiesBitmap = 0x10
)

type OptionsBitmap uint8

const (
	OptionsBitmapExecuteIfOff OptionsBitmap = 0x1
)

type UpdateFlagsBitmap uint8

const (
	UpdateFlagsBitmapUpdateAction UpdateFlagsBitmap = 0x1
	UpdateFlagsBitmapUpdateDirection UpdateFlagsBitmap = 0x2
	UpdateFlagsBitmapUpdateTime UpdateFlagsBitmap = 0x4
	UpdateFlagsBitmapUpdateStartHue UpdateFlagsBitmap = 0x8
)



