// Code generated by data_gen.go. DO NOT EDIT.

package appobserver

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type StatusEnum uint8

const (
	StatusEnumSuccess StatusEnum = 0
	StatusEnumUnexpectedData StatusEnum = 1
)



