// Code generated by data_gen.go. DO NOT EDIT.

package opcreds

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type CertificateChainTypeEnum uint8

const (
	CertificateChainTypeEnumDACCertificate CertificateChainTypeEnum = 1
	CertificateChainTypeEnumPAICertificate CertificateChainTypeEnum = 2
)

type NodeOperationalCertStatusEnum uint8

const (
	NodeOperationalCertStatusEnumOK NodeOperationalCertStatusEnum = 0
	NodeOperationalCertStatusEnumInvalidPublicKey NodeOperationalCertStatusEnum = 1
	NodeOperationalCertStatusEnumInvalidNodeOpId NodeOperationalCertStatusEnum = 2
	NodeOperationalCertStatusEnumInvalidNOC NodeOperationalCertStatusEnum = 3
	NodeOperationalCertStatusEnumMissingCsr NodeOperationalCertStatusEnum = 4
	NodeOperationalCertStatusEnumTableFull NodeOperationalCertStatusEnum = 5
	NodeOperationalCertStatusEnumInvalidAdminSubject NodeOperationalCertStatusEnum = 6
	NodeOperationalCertStatusEnumFabricConflict NodeOperationalCertStatusEnum = 9
	NodeOperationalCertStatusEnumLabelConflict NodeOperationalCertStatusEnum = 10
	NodeOperationalCertStatusEnumInvalidFabricIndex NodeOperationalCertStatusEnum = 11
)



type FabricDescriptor struct {
	RootPublicKey []byte // Tag 1
	VendorID dm.VendorID // Tag 2
	FabricID dm.FabricID // Tag 3
	NodeID dm.NodeID // Tag 4
	Label string // Tag 5
	VIDVerificationStatement *[]byte // Tag 6
}

func (s *FabricDescriptor) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: RootPublicKey Tag: 1
    
        st[tlv.ContextTag(1)] = []byte(s.RootPublicKey)
    
	// Field: VendorID Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.VendorID)
    
	// Field: FabricID Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.FabricID)
    
	// Field: NodeID Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.NodeID)
    
	// Field: Label Tag: 5
    
        st[tlv.ContextTag(5)] = (s.Label)
    
	// Field: VIDVerificationStatement Tag: 6
    if s.VIDVerificationStatement != nil {
        st[tlv.ContextTag(6)] = []byte(*s.VIDVerificationStatement)
    }
	return st
}

func (s *FabricDescriptor) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.RootPublicKey = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.VendorID(v)
s.VendorID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.FabricID(v)
s.FabricID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.NodeID(v)
s.NodeID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Label = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(6)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.VIDVerificationStatement = &v
}
        
        
	}

    return nil
}

type NOC struct {
	NOC []byte // Tag 1
	ICAC *[]byte // Tag 2
	VVSC []byte // Tag 3
}

func (s *NOC) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: NOC Tag: 1
    
        st[tlv.ContextTag(1)] = []byte(s.NOC)
    
	// Field: ICAC Tag: 2
    if s.ICAC != nil {
        st[tlv.ContextTag(2)] = []byte(*s.ICAC)
    }
	// Field: VVSC Tag: 3
    
        st[tlv.ContextTag(3)] = []byte(s.VVSC)
    
	return st
}

func (s *NOC) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.NOC = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.ICAC = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.VVSC = v
}
        
        
	}

    return nil
}

