// Code generated by data_gen.go. DO NOT EDIT.

package mediainput

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type InputTypeEnum uint8

const (
	InputTypeEnumInternal InputTypeEnum = 0
	InputTypeEnumAux InputTypeEnum = 1
	InputTypeEnumCoax InputTypeEnum = 2
	InputTypeEnumComposite InputTypeEnum = 3
	InputTypeEnumHDMI InputTypeEnum = 4
	InputTypeEnumInput InputTypeEnum = 5
	InputTypeEnumLine InputTypeEnum = 6
	InputTypeEnumOptical InputTypeEnum = 7
	InputTypeEnumVideo InputTypeEnum = 8
	InputTypeEnumSCART InputTypeEnum = 9
	InputTypeEnumUSB InputTypeEnum = 10
	InputTypeEnumOther InputTypeEnum = 11
)



type InputInfo struct {
	Index uint8 // Tag 0
	InputType InputTypeEnum // Tag 1
	Name string // Tag 2
	Description string // Tag 3
}

func (s *InputInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Index Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.Index)
    
	// Field: InputType Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.InputType)
    
	// Field: Name Tag: 2
    
        st[tlv.ContextTag(2)] = (s.Name)
    
	// Field: Description Tag: 3
    
        st[tlv.ContextTag(3)] = (s.Description)
    
	return st
}

func (s *InputInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.Index = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := InputTypeEnum(v)
s.InputType = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Description = v
}
        
        
	}

    return nil
}

