// Code generated by data_gen.go. DO NOT EDIT.

package bind

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()







type Target struct {
	Node dm.NodeID // Tag 1
	Group dm.GroupID // Tag 2
	Endpoint dm.EndpointID // Tag 3
	Cluster *dm.ClusterID // Tag 4
}

func (s *Target) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Node Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Node)
    
	// Field: Group Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.Group)
    
	// Field: Endpoint Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.Endpoint)
    
	// Field: Cluster Tag: 4
    if s.Cluster != nil {
        st[tlv.ContextTag(4)] = uint64(*s.Cluster)
    }
	return st
}

func (s *Target) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.NodeID(v)
s.Node = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.GroupID(v)
s.Group = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EndpointID(v)
s.Endpoint = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.ClusterID(v)
s.Cluster = &casted
}
        
        
	}

    return nil
}

