// Code generated by data_gen.go. DO NOT EDIT.

package ltime

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type CalendarTypeEnum uint8

const (
	CalendarTypeEnumBuddhist CalendarTypeEnum = 0
	CalendarTypeEnumChinese CalendarTypeEnum = 1
	CalendarTypeEnumCoptic CalendarTypeEnum = 2
	CalendarTypeEnumEthiopian CalendarTypeEnum = 3
	CalendarTypeEnumGregorian CalendarTypeEnum = 4
	CalendarTypeEnumHebrew CalendarTypeEnum = 5
	CalendarTypeEnumIndian CalendarTypeEnum = 6
	CalendarTypeEnumIslamic CalendarTypeEnum = 7
	CalendarTypeEnumJapanese CalendarTypeEnum = 8
	CalendarTypeEnumKorean CalendarTypeEnum = 9
	CalendarTypeEnumPersian CalendarTypeEnum = 10
	CalendarTypeEnumTaiwanese CalendarTypeEnum = 11
	CalendarTypeEnumUseActiveLocale CalendarTypeEnum = 255
)

type HourFormatEnum uint8

const (
	HourFormatEnum12hr HourFormatEnum = 0
	HourFormatEnum24hr HourFormatEnum = 1
	HourFormatEnumUseActiveLocale HourFormatEnum = 255
)



