// Code generated by data_gen.go. DO NOT EDIT.

package smokeco

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type AlarmStateEnum uint8

const (
	AlarmStateEnumNormal AlarmStateEnum = 0
	AlarmStateEnumWarning AlarmStateEnum = 1
	AlarmStateEnumCritical AlarmStateEnum = 2
)

type ContaminationStateEnum uint8

const (
	ContaminationStateEnumNormal ContaminationStateEnum = 0
	ContaminationStateEnumLow ContaminationStateEnum = 1
	ContaminationStateEnumWarning ContaminationStateEnum = 2
	ContaminationStateEnumCritical ContaminationStateEnum = 3
)

type EndOfServiceEnum uint8

const (
	EndOfServiceEnumNormal EndOfServiceEnum = 0
	EndOfServiceEnumExpired EndOfServiceEnum = 1
)

type ExpressedStateEnum uint8

const (
	ExpressedStateEnumNormal ExpressedStateEnum = 0
	ExpressedStateEnumSmokeAlarm ExpressedStateEnum = 1
	ExpressedStateEnumCOAlarm ExpressedStateEnum = 2
	ExpressedStateEnumBatteryAlert ExpressedStateEnum = 3
	ExpressedStateEnumTesting ExpressedStateEnum = 4
	ExpressedStateEnumHardwareFault ExpressedStateEnum = 5
	ExpressedStateEnumEndOfService ExpressedStateEnum = 6
	ExpressedStateEnumInterconnectSmoke ExpressedStateEnum = 7
	ExpressedStateEnumInterconnectCO ExpressedStateEnum = 8
)

type MuteStateEnum uint8

const (
	MuteStateEnumNotMuted MuteStateEnum = 0
	MuteStateEnumMuted MuteStateEnum = 1
)

type SensitivityEnum uint8

const (
	SensitivityEnumHigh SensitivityEnum = 0
	SensitivityEnumStandard SensitivityEnum = 1
	SensitivityEnumLow SensitivityEnum = 2
)



