// Code generated by data_gen.go. DO NOT EDIT.

package concon

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type StatusCodeEnum uint8

const (
	StatusCodeEnumInvalidPINCode StatusCodeEnum = 0x02
	StatusCodeEnumInvalidRating StatusCodeEnum = 0x03
	StatusCodeEnumInvalidChannel StatusCodeEnum = 0x04
	StatusCodeEnumChannelAlreadyExist StatusCodeEnum = 0x05
	StatusCodeEnumChannelNotExist StatusCodeEnum = 0x06
	StatusCodeEnumUnidentifiableApplication StatusCodeEnum = 0x07
	StatusCodeEnumApplicationAlreadyExist StatusCodeEnum = 0x08
	StatusCodeEnumApplicationNotExist StatusCodeEnum = 0x09
	StatusCodeEnumTimeWindowAlreadyExist StatusCodeEnum = 0x0A
	StatusCodeEnumTimeWindowNotExist StatusCodeEnum = 0x0B
)

type DayOfWeekBitmap uint8

const (
	DayOfWeekBitmapSunday DayOfWeekBitmap = 0x1
	DayOfWeekBitmapMonday DayOfWeekBitmap = 0x2
	DayOfWeekBitmapTuesday DayOfWeekBitmap = 0x4
	DayOfWeekBitmapWednesday DayOfWeekBitmap = 0x8
	DayOfWeekBitmapThursday DayOfWeekBitmap = 0x10
	DayOfWeekBitmapFriday DayOfWeekBitmap = 0x20
	DayOfWeekBitmapSaturday DayOfWeekBitmap = 0x40
)



type AppInfo struct {
	CatalogVendorID uint16 // Tag 0
	ApplicationID string // Tag 1
}

func (s *AppInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: CatalogVendorID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.CatalogVendorID)
    
	// Field: ApplicationID Tag: 1
    
        st[tlv.ContextTag(1)] = (s.ApplicationID)
    
	return st
}

func (s *AppInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.CatalogVendorID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.ApplicationID = v
}
        
        
	}

    return nil
}

type BlockChannel struct {
	BlockChannelIndex *uint16 // Tag 0
	MajorNumber uint16 // Tag 1
	MinorNumber uint16 // Tag 2
	Identifier *string // Tag 3
}

func (s *BlockChannel) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: BlockChannelIndex Tag: 0
    if s.BlockChannelIndex != nil {
        st[tlv.ContextTag(0)] = uint64(*s.BlockChannelIndex)
    }
	// Field: MajorNumber Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.MajorNumber)
    
	// Field: MinorNumber Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.MinorNumber)
    
	// Field: Identifier Tag: 3
    if s.Identifier != nil {
        st[tlv.ContextTag(3)] = (*s.Identifier)
    }
	return st
}

func (s *BlockChannel) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.BlockChannelIndex = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.MajorNumber = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.MinorNumber = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Identifier = &v
}
        
        
	}

    return nil
}

type RatingName struct {
	RatingName string // Tag 0
	RatingNameDesc *string // Tag 1
}

func (s *RatingName) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: RatingName Tag: 0
    
        st[tlv.ContextTag(0)] = (s.RatingName)
    
	// Field: RatingNameDesc Tag: 1
    if s.RatingNameDesc != nil {
        st[tlv.ContextTag(1)] = (*s.RatingNameDesc)
    }
	return st
}

func (s *RatingName) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(string); ok {
s.RatingName = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.RatingNameDesc = &v
}
        
        
	}

    return nil
}

type TimePeriod struct {
	StartHour uint8 // Tag 0
	StartMinute uint8 // Tag 1
	EndHour uint8 // Tag 2
	EndMinute uint8 // Tag 3
}

func (s *TimePeriod) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: StartHour Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.StartHour)
    
	// Field: StartMinute Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.StartMinute)
    
	// Field: EndHour Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.EndHour)
    
	// Field: EndMinute Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.EndMinute)
    
	return st
}

func (s *TimePeriod) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.StartHour = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.StartMinute = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.EndHour = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.EndMinute = casted
}
        
        
	}

    return nil
}

type TimeWindow struct {
	TimeWindowIndex *uint16 // Tag 0
	DayOfWeek DayOfWeekBitmap // Tag 1
	TimePeriod []TimePeriod // Tag 2
}

func (s *TimeWindow) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: TimeWindowIndex Tag: 0
    if s.TimeWindowIndex != nil {
        st[tlv.ContextTag(0)] = uint64(*s.TimeWindowIndex)
    }
	// Field: DayOfWeek Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.DayOfWeek)
    
	// Field: TimePeriod Tag: 2
    if len(s.TimePeriod) > 0 {
        
        list := make(tlv.StructArray, 0, len(s.TimePeriod))
        for _, v := range s.TimePeriod {
            list = append(list, v.Encode())
        }
        st[tlv.ContextTag(2)] = list
        
    }
	return st
}

func (s *TimeWindow) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.TimeWindowIndex = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := DayOfWeekBitmap(v)
s.DayOfWeek = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
            
            if list, ok := val.(tlv.StructArray); ok {
                 for _, item := range list {
                    var newItem TimePeriod
                    if err := newItem.Decode(item); err != nil { return err }
                    s.TimePeriod = append(s.TimePeriod, newItem)
                 }
            }
            
        
	}

    return nil
}

