// Code generated by data_gen.go. DO NOT EDIT.

package cgen

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type CommissioningErrorEnum uint8

const (
	CommissioningErrorEnumOK CommissioningErrorEnum = 0
	CommissioningErrorEnumValueOutsideRange CommissioningErrorEnum = 1
	CommissioningErrorEnumInvalidAuthentication CommissioningErrorEnum = 2
	CommissioningErrorEnumNoFailSafe CommissioningErrorEnum = 3
	CommissioningErrorEnumBusyWithOtherAdmin CommissioningErrorEnum = 4
	CommissioningErrorEnumRequiredTCNotAccepted CommissioningErrorEnum = 5
	CommissioningErrorEnumTCAcknowledgementsNotReceived CommissioningErrorEnum = 6
	CommissioningErrorEnumTCMinVersionNotMet CommissioningErrorEnum = 7
)

type RegulatoryLocationTypeEnum uint8

const (
	RegulatoryLocationTypeEnumIndoor RegulatoryLocationTypeEnum = 0
	RegulatoryLocationTypeEnumOutdoor RegulatoryLocationTypeEnum = 1
	RegulatoryLocationTypeEnumIndoorOutdoor RegulatoryLocationTypeEnum = 2
)



type BasicCommissioningInfo struct {
	FailSafeExpiryLengthSeconds uint16 // Tag 0
	MaxCumulativeFailsafeSeconds uint16 // Tag 1
}

func (s *BasicCommissioningInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: FailSafeExpiryLengthSeconds Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.FailSafeExpiryLengthSeconds)
    
	// Field: MaxCumulativeFailsafeSeconds Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.MaxCumulativeFailsafeSeconds)
    
	return st
}

func (s *BasicCommissioningInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.FailSafeExpiryLengthSeconds = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.MaxCumulativeFailsafeSeconds = casted
}
        
        
	}

    return nil
}

