// Code generated by data_gen.go. DO NOT EDIT.

package dgwifi

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type AssociationFailureCauseEnum uint8

const (
	AssociationFailureCauseEnumUnknown AssociationFailureCauseEnum = 0
	AssociationFailureCauseEnumAssociationFailed AssociationFailureCauseEnum = 1
	AssociationFailureCauseEnumAuthenticationFailed AssociationFailureCauseEnum = 2
	AssociationFailureCauseEnumSsidNotFound AssociationFailureCauseEnum = 3
)

type ConnectionStatusEnum uint8

const (
	ConnectionStatusEnumConnected ConnectionStatusEnum = 0
	ConnectionStatusEnumNotConnected ConnectionStatusEnum = 1
)

type SecurityTypeEnum uint8

const (
	SecurityTypeEnumUnspecified SecurityTypeEnum = 0
	SecurityTypeEnumNone SecurityTypeEnum = 1
	SecurityTypeEnumWEP SecurityTypeEnum = 2
	SecurityTypeEnumWPA SecurityTypeEnum = 3
	SecurityTypeEnumWPA2 SecurityTypeEnum = 4
	SecurityTypeEnumWPA3 SecurityTypeEnum = 5
)

type WiFiVersionEnum uint8

const (
	WiFiVersionEnuma WiFiVersionEnum = 0
	WiFiVersionEnumb WiFiVersionEnum = 1
	WiFiVersionEnumg WiFiVersionEnum = 2
	WiFiVersionEnumn WiFiVersionEnum = 3
	WiFiVersionEnumac WiFiVersionEnum = 4
	WiFiVersionEnumax WiFiVersionEnum = 5
	WiFiVersionEnumah WiFiVersionEnum = 6
)



