// Code generated by data_gen.go. DO NOT EDIT.

package tsuic

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type KeypadLockoutEnum uint8

const (
	KeypadLockoutEnumNoLockout KeypadLockoutEnum = 0
	KeypadLockoutEnumLockout1 KeypadLockoutEnum = 1
	KeypadLockoutEnumLockout2 KeypadLockoutEnum = 2
	KeypadLockoutEnumLockout3 KeypadLockoutEnum = 3
	KeypadLockoutEnumLockout4 KeypadLockoutEnum = 4
	KeypadLockoutEnumLockout5 KeypadLockoutEnum = 5
)

type ScheduleProgrammingVisibilityEnum uint8

const (
	ScheduleProgrammingVisibilityEnumScheduleProgrammingPermitted ScheduleProgrammingVisibilityEnum = 0
	ScheduleProgrammingVisibilityEnumScheduleProgrammingDenied ScheduleProgrammingVisibilityEnum = 1
)

type TemperatureDisplayModeEnum uint8

const (
	TemperatureDisplayModeEnumCelsius TemperatureDisplayModeEnum = 0
	TemperatureDisplayModeEnumFahrenheit TemperatureDisplayModeEnum = 1
)



