// Code generated by data_gen.go. DO NOT EDIT.

package g

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type NameSupportBitmap uint8

const (
	NameSupportBitmapGroupNames NameSupportBitmap = 0x80
)



