// Code generated by data_gen.go. DO NOT EDIT.

package tgtnav

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type StatusEnum uint8

const (
	StatusEnumSuccess StatusEnum = 0
	StatusEnumTargetNotFound StatusEnum = 1
	StatusEnumNotAllowed StatusEnum = 2
)



type TargetInfo struct {
	Identifier uint8 // Tag 0
	Name string // Tag 1
}

func (s *TargetInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Identifier Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.Identifier)
    
	// Field: Name Tag: 1
    
        st[tlv.ContextTag(1)] = (s.Name)
    
	return st
}

func (s *TargetInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.Identifier = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = v
}
        
        
	}

    return nil
}

