// Code generated by data_gen.go. DO NOT EDIT.

package dgthread

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ConnectionStatusEnum uint8

const (
	ConnectionStatusEnumConnected ConnectionStatusEnum = 0
	ConnectionStatusEnumNotConnected ConnectionStatusEnum = 1
)

type NetworkFaultEnum uint8

const (
	NetworkFaultEnumUnspecified NetworkFaultEnum = 0
	NetworkFaultEnumLinkDown NetworkFaultEnum = 1
	NetworkFaultEnumHardwareFailure NetworkFaultEnum = 2
	NetworkFaultEnumNetworkJammed NetworkFaultEnum = 3
)

type RoutingRoleEnum uint8

const (
	RoutingRoleEnumUnspecified RoutingRoleEnum = 0
	RoutingRoleEnumUnassigned RoutingRoleEnum = 1
	RoutingRoleEnumSleepyEndDevice RoutingRoleEnum = 2
	RoutingRoleEnumEndDevice RoutingRoleEnum = 3
	RoutingRoleEnumREED RoutingRoleEnum = 4
	RoutingRoleEnumRouter RoutingRoleEnum = 5
	RoutingRoleEnumLeader RoutingRoleEnum = 6
)



type NeighborTable struct {
	ExtAddress uint64 // Tag 0
	Age uint32 // Tag 1
	Rloc16 uint16 // Tag 2
	LinkFrameCounter uint32 // Tag 3
	MleFrameCounter uint32 // Tag 4
	LQI uint8 // Tag 5
	AverageRssi *int8 // Tag 6
	LastRssi *int8 // Tag 7
	FrameErrorRate uint8 // Tag 8
	MessageErrorRate uint8 // Tag 9
	RxOnWhenIdle bool // Tag 10
	FullThreadDevice bool // Tag 11
	FullNetworkData bool // Tag 12
	IsChild bool // Tag 13
}

func (s *NeighborTable) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ExtAddress Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.ExtAddress)
    
	// Field: Age Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Age)
    
	// Field: Rloc16 Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.Rloc16)
    
	// Field: LinkFrameCounter Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.LinkFrameCounter)
    
	// Field: MleFrameCounter Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.MleFrameCounter)
    
	// Field: LQI Tag: 5
    
        st[tlv.ContextTag(5)] = uint64(s.LQI)
    
	// Field: AverageRssi Tag: 6
    if s.AverageRssi != nil {
        st[tlv.ContextTag(6)] = int64(*s.AverageRssi)
    }
	// Field: LastRssi Tag: 7
    if s.LastRssi != nil {
        st[tlv.ContextTag(7)] = int64(*s.LastRssi)
    }
	// Field: FrameErrorRate Tag: 8
    
        st[tlv.ContextTag(8)] = uint64(s.FrameErrorRate)
    
	// Field: MessageErrorRate Tag: 9
    
        st[tlv.ContextTag(9)] = uint64(s.MessageErrorRate)
    
	// Field: RxOnWhenIdle Tag: 10
    
        st[tlv.ContextTag(10)] = (s.RxOnWhenIdle)
    
	// Field: FullThreadDevice Tag: 11
    
        st[tlv.ContextTag(11)] = (s.FullThreadDevice)
    
	// Field: FullNetworkData Tag: 12
    
        st[tlv.ContextTag(12)] = (s.FullNetworkData)
    
	// Field: IsChild Tag: 13
    
        st[tlv.ContextTag(13)] = (s.IsChild)
    
	return st
}

func (s *NeighborTable) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint64(v)
s.ExtAddress = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.Age = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.Rloc16 = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.LinkFrameCounter = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.MleFrameCounter = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.LQI = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(6)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int8(v)
s.AverageRssi = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(7)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int8(v)
s.LastRssi = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(8)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.FrameErrorRate = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(9)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.MessageErrorRate = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(10)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.RxOnWhenIdle = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(11)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.FullThreadDevice = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(12)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.FullNetworkData = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(13)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.IsChild = v
}
        
        
	}

    return nil
}

type OperationalDatasetComponents struct {
	ActiveTimestampPresent bool // Tag 0
	PendingTimestampPresent bool // Tag 1
	MasterKeyPresent bool // Tag 2
	NetworkNamePresent bool // Tag 3
	ExtendedPanIdPresent bool // Tag 4
	MeshLocalPrefixPresent bool // Tag 5
	DelayPresent bool // Tag 6
	PanIdPresent bool // Tag 7
	ChannelPresent bool // Tag 8
	PskcPresent bool // Tag 9
	SecurityPolicyPresent bool // Tag 10
	ChannelMaskPresent bool // Tag 11
}

func (s *OperationalDatasetComponents) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ActiveTimestampPresent Tag: 0
    
        st[tlv.ContextTag(0)] = (s.ActiveTimestampPresent)
    
	// Field: PendingTimestampPresent Tag: 1
    
        st[tlv.ContextTag(1)] = (s.PendingTimestampPresent)
    
	// Field: MasterKeyPresent Tag: 2
    
        st[tlv.ContextTag(2)] = (s.MasterKeyPresent)
    
	// Field: NetworkNamePresent Tag: 3
    
        st[tlv.ContextTag(3)] = (s.NetworkNamePresent)
    
	// Field: ExtendedPanIdPresent Tag: 4
    
        st[tlv.ContextTag(4)] = (s.ExtendedPanIdPresent)
    
	// Field: MeshLocalPrefixPresent Tag: 5
    
        st[tlv.ContextTag(5)] = (s.MeshLocalPrefixPresent)
    
	// Field: DelayPresent Tag: 6
    
        st[tlv.ContextTag(6)] = (s.DelayPresent)
    
	// Field: PanIdPresent Tag: 7
    
        st[tlv.ContextTag(7)] = (s.PanIdPresent)
    
	// Field: ChannelPresent Tag: 8
    
        st[tlv.ContextTag(8)] = (s.ChannelPresent)
    
	// Field: PskcPresent Tag: 9
    
        st[tlv.ContextTag(9)] = (s.PskcPresent)
    
	// Field: SecurityPolicyPresent Tag: 10
    
        st[tlv.ContextTag(10)] = (s.SecurityPolicyPresent)
    
	// Field: ChannelMaskPresent Tag: 11
    
        st[tlv.ContextTag(11)] = (s.ChannelMaskPresent)
    
	return st
}

func (s *OperationalDatasetComponents) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.ActiveTimestampPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.PendingTimestampPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.MasterKeyPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.NetworkNamePresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.ExtendedPanIdPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.MeshLocalPrefixPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(6)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.DelayPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(7)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.PanIdPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(8)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.ChannelPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(9)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.PskcPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(10)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.SecurityPolicyPresent = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(11)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.ChannelMaskPresent = v
}
        
        
	}

    return nil
}

type RouteTable struct {
	ExtAddress uint64 // Tag 0
	Rloc16 uint16 // Tag 1
	RouterId uint8 // Tag 2
	NextHop uint8 // Tag 3
	PathCost uint8 // Tag 4
	LQIIn uint8 // Tag 5
	LQIOut uint8 // Tag 6
	Age uint8 // Tag 7
	Allocated bool // Tag 8
	LinkEstablished bool // Tag 9
}

func (s *RouteTable) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ExtAddress Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.ExtAddress)
    
	// Field: Rloc16 Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Rloc16)
    
	// Field: RouterId Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.RouterId)
    
	// Field: NextHop Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.NextHop)
    
	// Field: PathCost Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.PathCost)
    
	// Field: LQIIn Tag: 5
    
        st[tlv.ContextTag(5)] = uint64(s.LQIIn)
    
	// Field: LQIOut Tag: 6
    
        st[tlv.ContextTag(6)] = uint64(s.LQIOut)
    
	// Field: Age Tag: 7
    
        st[tlv.ContextTag(7)] = uint64(s.Age)
    
	// Field: Allocated Tag: 8
    
        st[tlv.ContextTag(8)] = (s.Allocated)
    
	// Field: LinkEstablished Tag: 9
    
        st[tlv.ContextTag(9)] = (s.LinkEstablished)
    
	return st
}

func (s *RouteTable) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint64(v)
s.ExtAddress = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.Rloc16 = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.RouterId = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.NextHop = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.PathCost = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.LQIIn = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(6)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.LQIOut = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(7)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.Age = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(8)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.Allocated = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(9)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.LinkEstablished = v
}
        
        
	}

    return nil
}

type SecurityPolicy struct {
	RotationTime uint16 // Tag 0
	Flags uint16 // Tag 1
}

func (s *SecurityPolicy) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: RotationTime Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.RotationTime)
    
	// Field: Flags Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Flags)
    
	return st
}

func (s *SecurityPolicy) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.RotationTime = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.Flags = casted
}
        
        
	}

    return nil
}

