// Code generated by data_gen.go. DO NOT EDIT.

package washerctrl

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type NumberOfRinsesEnum uint8

const (
	NumberOfRinsesEnumNone NumberOfRinsesEnum = 0
	NumberOfRinsesEnumNormal NumberOfRinsesEnum = 1
	NumberOfRinsesEnumExtra NumberOfRinsesEnum = 2
	NumberOfRinsesEnumMax NumberOfRinsesEnum = 3
)



