// Code generated by data_gen.go. DO NOT EDIT.

package applauncher

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type StatusEnum uint8

const (
	StatusEnumSuccess StatusEnum = 0
	StatusEnumAppNotAvailable StatusEnum = 1
	StatusEnumSystemBusy StatusEnum = 2
	StatusEnumPendingUserApproval StatusEnum = 3
	StatusEnumDownloading StatusEnum = 4
	StatusEnumInstalling StatusEnum = 5
)



type ApplicationEP struct {
	Application Application // Tag 0
	Endpoint *dm.EndpointID // Tag 1
}

func (s *ApplicationEP) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Application Tag: 0
    
        st[tlv.ContextTag(0)] = s.Application.Encode()
        
    
	// Field: Endpoint Tag: 1
    if s.Endpoint != nil {
        st[tlv.ContextTag(1)] = uint64(*s.Endpoint)
    }
	return st
}

func (s *ApplicationEP) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        if err := s.Application.Decode(val); err != nil { return err }
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EndpointID(v)
s.Endpoint = &casted
}
        
        
	}

    return nil
}

type Application struct {
	CatalogVendorID uint16 // Tag 0
	ApplicationID string // Tag 1
}

func (s *Application) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: CatalogVendorID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.CatalogVendorID)
    
	// Field: ApplicationID Tag: 1
    
        st[tlv.ContextTag(1)] = (s.ApplicationID)
    
	return st
}

func (s *Application) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.CatalogVendorID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.ApplicationID = v
}
        
        
	}

    return nil
}

