// Code generated by data_gen.go. DO NOT EDIT.

package ewaterhtr

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type BoostStateEnum uint8

const (
	BoostStateEnumInactive BoostStateEnum = 0
	BoostStateEnumActive BoostStateEnum = 1
)

type WaterHeaterHeatSourceBitmap uint8

const (
	WaterHeaterHeatSourceBitmapImmersionElement1 WaterHeaterHeatSourceBitmap = 0x1
	WaterHeaterHeatSourceBitmapImmersionElement2 WaterHeaterHeatSourceBitmap = 0x2
	WaterHeaterHeatSourceBitmapHeatPump WaterHeaterHeatSourceBitmap = 0x4
	WaterHeaterHeatSourceBitmapBoiler WaterHeaterHeatSourceBitmap = 0x8
	WaterHeaterHeatSourceBitmapOther WaterHeaterHeatSourceBitmap = 0x10
)



type WaterHeaterBoostInfo struct {
	Duration dm.ElapsedS // Tag 0
	OneShot bool // Tag 1
	EmergencyBoost *bool // Tag 2
	TemporarySetpoint *dm.Temperature // Tag 3
	TargetPercentage dm.Percent // Tag 4
	TargetReheat *dm.Percent // Tag 5
}

func (s *WaterHeaterBoostInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Duration Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.Duration)
    
	// Field: OneShot Tag: 1
    
        st[tlv.ContextTag(1)] = (s.OneShot)
    
	// Field: EmergencyBoost Tag: 2
    if s.EmergencyBoost != nil {
        st[tlv.ContextTag(2)] = (*s.EmergencyBoost)
    }
	// Field: TemporarySetpoint Tag: 3
    if s.TemporarySetpoint != nil {
        st[tlv.ContextTag(3)] = int64(*s.TemporarySetpoint)
    }
	// Field: TargetPercentage Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.TargetPercentage)
    
	// Field: TargetReheat Tag: 5
    if s.TargetReheat != nil {
        st[tlv.ContextTag(5)] = uint64(*s.TargetReheat)
    }
	return st
}

func (s *WaterHeaterBoostInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.ElapsedS(v)
s.Duration = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.OneShot = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.EmergencyBoost = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := dm.Temperature(v)
s.TemporarySetpoint = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.Percent(v)
s.TargetPercentage = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.Percent(v)
s.TargetReheat = &casted
}
        
        
	}

    return nil
}

