// Code generated by data_gen.go. DO NOT EDIT.

package thnetdir

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()







type ThreadNetwork struct {
	ExtendedPanID []byte // Tag 0
	NetworkName string // Tag 1
	Channel uint16 // Tag 2
	ActiveTimestamp uint64 // Tag 3
}

func (s *ThreadNetwork) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ExtendedPanID Tag: 0
    
        st[tlv.ContextTag(0)] = []byte(s.ExtendedPanID)
    
	// Field: NetworkName Tag: 1
    
        st[tlv.ContextTag(1)] = (s.NetworkName)
    
	// Field: Channel Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.Channel)
    
	// Field: ActiveTimestamp Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.ActiveTimestamp)
    
	return st
}

func (s *ThreadNetwork) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.ExtendedPanID = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.NetworkName = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.Channel = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint64(v)
s.ActiveTimestamp = casted
}
        
        
	}

    return nil
}

