// Code generated by data_gen.go. DO NOT EDIT.

package epm

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type PowerModeEnum uint8

const (
	PowerModeEnumUnknown PowerModeEnum = 0
	PowerModeEnumDC PowerModeEnum = 1
	PowerModeEnumAC PowerModeEnum = 2
)



type HarmonicMeasurement struct {
	Order uint8 // Tag 0
	Measurement *int64 // Tag 1
}

func (s *HarmonicMeasurement) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Order Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.Order)
    
	// Field: Measurement Tag: 1
    if s.Measurement != nil {
        st[tlv.ContextTag(1)] = int64(*s.Measurement)
    }
	return st
}

func (s *HarmonicMeasurement) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.Order = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int64(v)
s.Measurement = &casted
}
        
        
	}

    return nil
}

type MeasurementRange struct {
	MeasurementType dm.MeasurementTypeEnum // Tag 0
	Min int64 // Tag 1
	Max int64 // Tag 2
	StartTimestamp dm.EpochS // Tag 3
	EndTimestamp dm.EpochS // Tag 4
	MinTimestamp dm.EpochS // Tag 5
	MaxTimestamp dm.EpochS // Tag 6
	StartSystime dm.SystemTimeMS // Tag 7
	EndSystime dm.SystemTimeMS // Tag 8
	MinSystime dm.SystemTimeMS // Tag 9
	MaxSystime dm.SystemTimeMS // Tag 10
}

func (s *MeasurementRange) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: MeasurementType Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.MeasurementType)
    
	// Field: Min Tag: 1
    
        st[tlv.ContextTag(1)] = int64(s.Min)
    
	// Field: Max Tag: 2
    
        st[tlv.ContextTag(2)] = int64(s.Max)
    
	// Field: StartTimestamp Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.StartTimestamp)
    
	// Field: EndTimestamp Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.EndTimestamp)
    
	// Field: MinTimestamp Tag: 5
    
        st[tlv.ContextTag(5)] = uint64(s.MinTimestamp)
    
	// Field: MaxTimestamp Tag: 6
    
        st[tlv.ContextTag(6)] = uint64(s.MaxTimestamp)
    
	// Field: StartSystime Tag: 7
    
        st[tlv.ContextTag(7)] = uint64(s.StartSystime)
    
	// Field: EndSystime Tag: 8
    
        st[tlv.ContextTag(8)] = uint64(s.EndSystime)
    
	// Field: MinSystime Tag: 9
    
        st[tlv.ContextTag(9)] = uint64(s.MinSystime)
    
	// Field: MaxSystime Tag: 10
    
        st[tlv.ContextTag(10)] = uint64(s.MaxSystime)
    
	return st
}

func (s *MeasurementRange) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.MeasurementTypeEnum(v)
s.MeasurementType = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int64(v)
s.Min = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int64(v)
s.Max = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EpochS(v)
s.StartTimestamp = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EpochS(v)
s.EndTimestamp = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EpochS(v)
s.MinTimestamp = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(6)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EpochS(v)
s.MaxTimestamp = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(7)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.SystemTimeMS(v)
s.StartSystime = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(8)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.SystemTimeMS(v)
s.EndSystime = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(9)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.SystemTimeMS(v)
s.MinSystime = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(10)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.SystemTimeMS(v)
s.MaxSystime = casted
}
        
        
	}

    return nil
}

