// Code generated by data_gen.go. DO NOT EDIT.

package cnet

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type NetworkCommissioningStatusEnum uint8

const (
	NetworkCommissioningStatusEnumSuccess NetworkCommissioningStatusEnum = 0
	NetworkCommissioningStatusEnumOutOfRange NetworkCommissioningStatusEnum = 1
	NetworkCommissioningStatusEnumBoundsExceeded NetworkCommissioningStatusEnum = 2
	NetworkCommissioningStatusEnumNetworkIDNotFound NetworkCommissioningStatusEnum = 3
	NetworkCommissioningStatusEnumDuplicateNetworkID NetworkCommissioningStatusEnum = 4
	NetworkCommissioningStatusEnumNetworkNotFound NetworkCommissioningStatusEnum = 5
	NetworkCommissioningStatusEnumRegulatoryError NetworkCommissioningStatusEnum = 6
	NetworkCommissioningStatusEnumAuthFailure NetworkCommissioningStatusEnum = 7
	NetworkCommissioningStatusEnumUnsupportedSecurity NetworkCommissioningStatusEnum = 8
	NetworkCommissioningStatusEnumOtherConnectionFailure NetworkCommissioningStatusEnum = 9
	NetworkCommissioningStatusEnumIPV6Failed NetworkCommissioningStatusEnum = 10
	NetworkCommissioningStatusEnumIPBindFailed NetworkCommissioningStatusEnum = 11
	NetworkCommissioningStatusEnumUnknownError NetworkCommissioningStatusEnum = 12
)

type WiFiBandEnum uint8

const (
	WiFiBandEnum2G4 WiFiBandEnum = 0
	WiFiBandEnum3G65 WiFiBandEnum = 1
	WiFiBandEnum5G WiFiBandEnum = 2
	WiFiBandEnum6G WiFiBandEnum = 3
	WiFiBandEnum60G WiFiBandEnum = 4
	WiFiBandEnum1G WiFiBandEnum = 5
)

type ThreadCapabilitiesBitmap uint8

const (
	ThreadCapabilitiesBitmapIsBorderRouterCapable ThreadCapabilitiesBitmap = 0x1
	ThreadCapabilitiesBitmapIsRouterCapable ThreadCapabilitiesBitmap = 0x2
	ThreadCapabilitiesBitmapIsSleepyEndDeviceCapable ThreadCapabilitiesBitmap = 0x4
	ThreadCapabilitiesBitmapIsFullThreadDevice ThreadCapabilitiesBitmap = 0x8
	ThreadCapabilitiesBitmapIsSynchronizedSleepyEndDeviceCapable ThreadCapabilitiesBitmap = 0x10
)

type WiFiSecurityBitmap uint8

const (
	WiFiSecurityBitmapUnencrypted WiFiSecurityBitmap = 0x1
	WiFiSecurityBitmapWEP WiFiSecurityBitmap = 0x2
	WiFiSecurityBitmapWPA_PERSONAL WiFiSecurityBitmap = 0x4
	WiFiSecurityBitmapWPA2_PERSONAL WiFiSecurityBitmap = 0x8
	WiFiSecurityBitmapWPA3_PERSONAL WiFiSecurityBitmap = 0x10
)



type NetworkInfo struct {
	NetworkID []byte // Tag 0
	Connected bool // Tag 1
}

func (s *NetworkInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: NetworkID Tag: 0
    
        st[tlv.ContextTag(0)] = []byte(s.NetworkID)
    
	// Field: Connected Tag: 1
    
        st[tlv.ContextTag(1)] = (s.Connected)
    
	return st
}

func (s *NetworkInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.NetworkID = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.Connected = v
}
        
        
	}

    return nil
}

type ThreadInterfaceScanResult struct {
	PanId uint16 // Tag 0
	ExtendedPanId uint64 // Tag 1
	NetworkName string // Tag 2
	Channel uint16 // Tag 3
	Version uint8 // Tag 4
	ExtendedAddress dm.HardwareAddress // Tag 5
	RSSI int8 // Tag 6
	LQI uint8 // Tag 7
}

func (s *ThreadInterfaceScanResult) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: PanId Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.PanId)
    
	// Field: ExtendedPanId Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.ExtendedPanId)
    
	// Field: NetworkName Tag: 2
    
        st[tlv.ContextTag(2)] = (s.NetworkName)
    
	// Field: Channel Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.Channel)
    
	// Field: Version Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.Version)
    
	// Field: ExtendedAddress Tag: 5
    
        st[tlv.ContextTag(5)] = []byte(s.ExtendedAddress)
    
	// Field: RSSI Tag: 6
    
        st[tlv.ContextTag(6)] = int64(s.RSSI)
    
	// Field: LQI Tag: 7
    
        st[tlv.ContextTag(7)] = uint64(s.LQI)
    
	return st
}

func (s *ThreadInterfaceScanResult) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.PanId = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint64(v)
s.ExtendedPanId = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(string); ok {
s.NetworkName = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.Channel = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.Version = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.ExtendedAddress = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(6)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int8(v)
s.RSSI = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(7)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.LQI = casted
}
        
        
	}

    return nil
}

type WiFiInterfaceScanResult struct {
	Security WiFiSecurityBitmap // Tag 0
	SSID []byte // Tag 1
	BSSID []byte // Tag 2
	Channel uint16 // Tag 3
	WiFiBand *WiFiBandEnum // Tag 4
	RSSI *int8 // Tag 5
}

func (s *WiFiInterfaceScanResult) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Security Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.Security)
    
	// Field: SSID Tag: 1
    
        st[tlv.ContextTag(1)] = []byte(s.SSID)
    
	// Field: BSSID Tag: 2
    
        st[tlv.ContextTag(2)] = []byte(s.BSSID)
    
	// Field: Channel Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.Channel)
    
	// Field: WiFiBand Tag: 4
    if s.WiFiBand != nil {
        st[tlv.ContextTag(4)] = uint64(*s.WiFiBand)
    }
	// Field: RSSI Tag: 5
    if s.RSSI != nil {
        st[tlv.ContextTag(5)] = int64(*s.RSSI)
    }
	return st
}

func (s *WiFiInterfaceScanResult) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := WiFiSecurityBitmap(v)
s.Security = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.SSID = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.BSSID = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.Channel = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := WiFiBandEnum(v)
s.WiFiBand = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int8(v)
s.RSSI = &casted
}
        
        
	}

    return nil
}

