// Code generated by data_gen.go. DO NOT EDIT.

package dishalm

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type AlarmBitmap uint8

const (
	AlarmBitmapInflowError AlarmBitmap = 0x1
	AlarmBitmapDrainError AlarmBitmap = 0x2
	AlarmBitmapDoorError AlarmBitmap = 0x4
	AlarmBitmapTempTooLow AlarmBitmap = 0x8
	AlarmBitmapTempTooHigh AlarmBitmap = 0x10
	AlarmBitmapWaterLevelError AlarmBitmap = 0x20
)



