// Code generated by data_gen.go. DO NOT EDIT.

package rvcrunm

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ModeTag uint16

const (
	ModeTagAuto ModeTag = 0x00
	ModeTagQuick ModeTag = 0x01
	ModeTagQuiet ModeTag = 0x02
	ModeTagLowNoise ModeTag = 0x03
	ModeTagLowEnergy ModeTag = 0x04
	ModeTagVacation ModeTag = 0x05
	ModeTagMin ModeTag = 0x06
	ModeTagMax ModeTag = 0x07
	ModeTagNight ModeTag = 0x08
	ModeTagDay ModeTag = 0x09
	ModeTagIdle ModeTag = 0x4000
	ModeTagCleaning ModeTag = 0x4001
	ModeTagMapping ModeTag = 0x4002
)

type StatusCodeEnum uint8

const (
	StatusCodeEnumStuck StatusCodeEnum = 0x41
	StatusCodeEnumDustBinMissing StatusCodeEnum = 0x42
	StatusCodeEnumDustBinFull StatusCodeEnum = 0x43
	StatusCodeEnumWaterTankEmpty StatusCodeEnum = 0x44
	StatusCodeEnumWaterTankMissing StatusCodeEnum = 0x45
	StatusCodeEnumWaterTankLidOpen StatusCodeEnum = 0x46
	StatusCodeEnumMopCleaningPadMissing StatusCodeEnum = 0x47
	StatusCodeEnumBatteryLow StatusCodeEnum = 0x48
)



