// Code generated by data_gen.go. DO NOT EDIT.

package apbsc

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ApplicationStatusEnum uint8

const (
	ApplicationStatusEnumStopped ApplicationStatusEnum = 0
	ApplicationStatusEnumActiveVisibleFocus ApplicationStatusEnum = 1
	ApplicationStatusEnumActiveHidden ApplicationStatusEnum = 2
	ApplicationStatusEnumActiveVisibleNotFocus ApplicationStatusEnum = 3
)



type Application struct {
	CatalogVendorID uint16 // Tag 0
	ApplicationID string // Tag 1
}

func (s *Application) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: CatalogVendorID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.CatalogVendorID)
    
	// Field: ApplicationID Tag: 1
    
        st[tlv.ContextTag(1)] = (s.ApplicationID)
    
	return st
}

func (s *Application) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.CatalogVendorID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.ApplicationID = v
}
        
        
	}

    return nil
}

