// Code generated by data_gen.go. DO NOT EDIT.

package epref

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type EnergyPriorityEnum uint8

const (
	EnergyPriorityEnumComfort EnergyPriorityEnum = 0
	EnergyPriorityEnumSpeed EnergyPriorityEnum = 1
	EnergyPriorityEnumEfficiency EnergyPriorityEnum = 2
	EnergyPriorityEnumWaterConsumption EnergyPriorityEnum = 3
)



type Balance struct {
	Step dm.Percent // Tag 0
	Label *string // Tag 1
}

func (s *Balance) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Step Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.Step)
    
	// Field: Label Tag: 1
    if s.Label != nil {
        st[tlv.ContextTag(1)] = (*s.Label)
    }
	return st
}

func (s *Balance) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.Percent(v)
s.Step = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Label = &v
}
        
        
	}

    return nil
}

