// Code generated by data_gen.go. DO NOT EDIT.

package label

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()







type Label struct {
	Label string // Tag 0
	Value string // Tag 1
}

func (s *Label) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Label Tag: 0
    
        st[tlv.ContextTag(0)] = (s.Label)
    
	// Field: Value Tag: 1
    
        st[tlv.ContextTag(1)] = (s.Value)
    
	return st
}

func (s *Label) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Label = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Value = v
}
        
        
	}

    return nil
}

