// Code generated by data_gen.go. DO NOT EDIT.

package audiooutput

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type OutputTypeEnum uint8

const (
	OutputTypeEnumHDMI OutputTypeEnum = 0
	OutputTypeEnumBT OutputTypeEnum = 1
	OutputTypeEnumOptical OutputTypeEnum = 2
	OutputTypeEnumHeadphone OutputTypeEnum = 3
	OutputTypeEnumInternal OutputTypeEnum = 4
	OutputTypeEnumOther OutputTypeEnum = 5
)



type OutputInfo struct {
	Index uint8 // Tag 0
	OutputType OutputTypeEnum // Tag 1
	Name string // Tag 2
}

func (s *OutputInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Index Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.Index)
    
	// Field: OutputType Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.OutputType)
    
	// Field: Name Tag: 2
    
        st[tlv.ContextTag(2)] = (s.Name)
    
	return st
}

func (s *OutputInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.Index = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := OutputTypeEnum(v)
s.OutputType = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = v
}
        
        
	}

    return nil
}

