// Code generated by data_gen.go. DO NOT EDIT.

package pcc

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ControlModeEnum uint8

const (
	ControlModeEnumConstantSpeed ControlModeEnum = 0
	ControlModeEnumConstantPressure ControlModeEnum = 1
	ControlModeEnumProportionalPressure ControlModeEnum = 2
	ControlModeEnumConstantFlow ControlModeEnum = 3
	ControlModeEnumConstantTemperature ControlModeEnum = 5
	ControlModeEnumAutomatic ControlModeEnum = 7
)

type OperationModeEnum uint8

const (
	OperationModeEnumNormal OperationModeEnum = 0
	OperationModeEnumMinimum OperationModeEnum = 1
	OperationModeEnumMaximum OperationModeEnum = 2
	OperationModeEnumLocal OperationModeEnum = 3
)

type PumpStatusBitmap uint16

const (
	PumpStatusBitmapDeviceFault PumpStatusBitmap = 0x1
	PumpStatusBitmapSupplyFault PumpStatusBitmap = 0x2
	PumpStatusBitmapSpeedLow PumpStatusBitmap = 0x4
	PumpStatusBitmapSpeedHigh PumpStatusBitmap = 0x8
	PumpStatusBitmapLocalOverride PumpStatusBitmap = 0x10
	PumpStatusBitmapRunning PumpStatusBitmap = 0x20
	PumpStatusBitmapRemotePressure PumpStatusBitmap = 0x40
	PumpStatusBitmapRemoteFlow PumpStatusBitmap = 0x80
	PumpStatusBitmapRemoteTemperature PumpStatusBitmap = 0x100
)



