// Code generated by data_gen.go. DO NOT EDIT.

package oo

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type DelayedAllOffEffectVariantEnum uint8

const (
	DelayedAllOffEffectVariantEnumDelayedOffFastFade DelayedAllOffEffectVariantEnum = 0x00
	DelayedAllOffEffectVariantEnumNoFade DelayedAllOffEffectVariantEnum = 0x01
	DelayedAllOffEffectVariantEnumDelayedOffSlowFade DelayedAllOffEffectVariantEnum = 0x02
)

type DyingLightEffectVariantEnum uint8

const (
	DyingLightEffectVariantEnumDyingLightFadeOff DyingLightEffectVariantEnum = 0x00
)

type EffectIdentifierEnum uint8

const (
	EffectIdentifierEnumDelayedAllOff EffectIdentifierEnum = 0x00
	EffectIdentifierEnumDyingLight EffectIdentifierEnum = 0x01
)

type StartUpOnOffEnum uint8

const (
	StartUpOnOffEnumOff StartUpOnOffEnum = 0
	StartUpOnOffEnumOn StartUpOnOffEnum = 1
	StartUpOnOffEnumToggle StartUpOnOffEnum = 2
)

type OnOffControlBitmap uint8

const (
	OnOffControlBitmapAcceptOnlyWhenOn OnOffControlBitmap = 0x1
)



