// Code generated by data_gen.go. DO NOT EDIT.

package ecoinfo

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()







type DeviceType struct {
	DeviceType dm.DeviceTypeID // Tag 0
	Revision uint16 // Tag 1
}

func (s *DeviceType) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: DeviceType Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.DeviceType)
    
	// Field: Revision Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Revision)
    
	return st
}

func (s *DeviceType) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.DeviceTypeID(v)
s.DeviceType = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.Revision = casted
}
        
        
	}

    return nil
}

type EcosystemDevice struct {
	DeviceName *string // Tag 0
	DeviceNameLastEdit dm.EpochUS // Tag 1
	BridgedEndpoint dm.EndpointID // Tag 2
	OriginalEndpoint dm.EndpointID // Tag 3
	DeviceTypes []DeviceType // Tag 4
	UniqueLocationIDs []string // Tag 5
	UniqueLocationIDsLastEdit dm.EpochUS // Tag 6
}

func (s *EcosystemDevice) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: DeviceName Tag: 0
    if s.DeviceName != nil {
        st[tlv.ContextTag(0)] = (*s.DeviceName)
    }
	// Field: DeviceNameLastEdit Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.DeviceNameLastEdit)
    
	// Field: BridgedEndpoint Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.BridgedEndpoint)
    
	// Field: OriginalEndpoint Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.OriginalEndpoint)
    
	// Field: DeviceTypes Tag: 4
    if len(s.DeviceTypes) > 0 {
        
        list := make(tlv.StructArray, 0, len(s.DeviceTypes))
        for _, v := range s.DeviceTypes {
            list = append(list, v.Encode())
        }
        st[tlv.ContextTag(4)] = list
        
    }
	// Field: UniqueLocationIDs Tag: 5
    if len(s.UniqueLocationIDs) > 0 {
        
        list := make(tlv.StringArray, 0, len(s.UniqueLocationIDs))
        for _, v := range s.UniqueLocationIDs {
            list = append(list, (v))
        }
        st[tlv.ContextTag(5)] = list
        
    }
	// Field: UniqueLocationIDsLastEdit Tag: 6
    
        st[tlv.ContextTag(6)] = uint64(s.UniqueLocationIDsLastEdit)
    
	return st
}

func (s *EcosystemDevice) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(string); ok {
s.DeviceName = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EpochUS(v)
s.DeviceNameLastEdit = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EndpointID(v)
s.BridgedEndpoint = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EndpointID(v)
s.OriginalEndpoint = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
            
            if list, ok := val.(tlv.StructArray); ok {
                 for _, item := range list {
                    var newItem DeviceType
                    if err := newItem.Decode(item); err != nil { return err }
                    s.DeviceTypes = append(s.DeviceTypes, newItem)
                 }
            }
            
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
            
            if arr, ok := val.(tlv.StringArray); ok {
                 for _, item := range arr {
                     s.UniqueLocationIDs = append(s.UniqueLocationIDs, string(item))
                 }
            }
            
        
	}
	if val, ok := st[tlv.ContextTag(6)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EpochUS(v)
s.UniqueLocationIDsLastEdit = casted
}
        
        
	}

    return nil
}

type EcosystemLocation struct {
	UniqueLocationID string // Tag 0
	LocationDescriptor dm.LocationDescriptor // Tag 1
	LocationDescriptorLastEdit dm.EpochUS // Tag 2
}

func (s *EcosystemLocation) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: UniqueLocationID Tag: 0
    
        st[tlv.ContextTag(0)] = (s.UniqueLocationID)
    
	// Field: LocationDescriptor Tag: 1
    
        st[tlv.ContextTag(1)] = s.LocationDescriptor.Encode()
        
    
	// Field: LocationDescriptorLastEdit Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.LocationDescriptorLastEdit)
    
	return st
}

func (s *EcosystemLocation) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(string); ok {
s.UniqueLocationID = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        if err := s.LocationDescriptor.Decode(val); err != nil { return err }
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EpochUS(v)
s.LocationDescriptorLastEdit = casted
}
        
        
	}

    return nil
}

