// Code generated by data_gen.go. DO NOT EDIT.

package airqual

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type AirQualityEnum uint8

const (
	AirQualityEnumUnknown AirQualityEnum = 0
	AirQualityEnumGood AirQualityEnum = 1
	AirQualityEnumFair AirQualityEnum = 2
	AirQualityEnumModerate AirQualityEnum = 3
	AirQualityEnumPoor AirQualityEnum = 4
	AirQualityEnumVeryPoor AirQualityEnum = 5
	AirQualityEnumExtremelyPoor AirQualityEnum = 6
)



