// Code generated by data_gen.go. DO NOT EDIT.

package opstate

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ErrorStateEnum uint8

const (
	ErrorStateEnumNoError ErrorStateEnum = 0x00
	ErrorStateEnumUnableToStartOrResume ErrorStateEnum = 0x01
	ErrorStateEnumUnableToCompleteOperation ErrorStateEnum = 0x02
	ErrorStateEnumCommandInvalidInState ErrorStateEnum = 0x03
)

type OperationalStateEnum uint8

const (
	OperationalStateEnumStopped OperationalStateEnum = 0x00
	OperationalStateEnumRunning OperationalStateEnum = 0x01
	OperationalStateEnumPaused OperationalStateEnum = 0x02
	OperationalStateEnumError OperationalStateEnum = 0x03
)



type ErrorState struct {
	ErrorStateID ErrorStateEnum // Tag 0
	ErrorStateLabel string // Tag 1
	ErrorStateDetails *string // Tag 2
}

func (s *ErrorState) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ErrorStateID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.ErrorStateID)
    
	// Field: ErrorStateLabel Tag: 1
    
        st[tlv.ContextTag(1)] = (s.ErrorStateLabel)
    
	// Field: ErrorStateDetails Tag: 2
    if s.ErrorStateDetails != nil {
        st[tlv.ContextTag(2)] = (*s.ErrorStateDetails)
    }
	return st
}

func (s *ErrorState) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ErrorStateEnum(v)
s.ErrorStateID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.ErrorStateLabel = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(string); ok {
s.ErrorStateDetails = &v
}
        
        
	}

    return nil
}

type OperationalState struct {
	OperationalStateID OperationalStateEnum // Tag 0
	OperationalStateLabel string // Tag 1
}

func (s *OperationalState) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: OperationalStateID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.OperationalStateID)
    
	// Field: OperationalStateLabel Tag: 1
    
        st[tlv.ContextTag(1)] = (s.OperationalStateLabel)
    
	return st
}

func (s *OperationalState) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := OperationalStateEnum(v)
s.OperationalStateID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.OperationalStateLabel = v
}
        
        
	}

    return nil
}

