// Code generated by data_gen.go. DO NOT EDIT.

package eevse

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type EnergyTransferStoppedReasonEnum uint8

const (
	EnergyTransferStoppedReasonEnumEVStopped EnergyTransferStoppedReasonEnum = 0
	EnergyTransferStoppedReasonEnumEVSEStopped EnergyTransferStoppedReasonEnum = 1
	EnergyTransferStoppedReasonEnumOther EnergyTransferStoppedReasonEnum = 2
)

type FaultStateEnum uint8

const (
	FaultStateEnumNoError FaultStateEnum = 0
	FaultStateEnumMeterFailure FaultStateEnum = 1
	FaultStateEnumOverVoltage FaultStateEnum = 2
	FaultStateEnumUnderVoltage FaultStateEnum = 3
	FaultStateEnumOverCurrent FaultStateEnum = 4
	FaultStateEnumContactWetFailure FaultStateEnum = 5
	FaultStateEnumContactDryFailure FaultStateEnum = 6
	FaultStateEnumGroundFault FaultStateEnum = 7
	FaultStateEnumPowerLoss FaultStateEnum = 8
	FaultStateEnumPowerQuality FaultStateEnum = 9
	FaultStateEnumPilotShortCircuit FaultStateEnum = 10
	FaultStateEnumEmergencyStop FaultStateEnum = 11
	FaultStateEnumEVDisconnected FaultStateEnum = 12
	FaultStateEnumWrongPowerSupply FaultStateEnum = 13
	FaultStateEnumLiveNeutralSwap FaultStateEnum = 14
	FaultStateEnumOverTemperature FaultStateEnum = 15
	FaultStateEnumOther FaultStateEnum = 255
)

type StateEnum uint8

const (
	StateEnumNotPluggedIn StateEnum = 0
	StateEnumPluggedInNoDemand StateEnum = 1
	StateEnumPluggedInDemand StateEnum = 2
	StateEnumPluggedInCharging StateEnum = 3
	StateEnumPluggedInDischarging StateEnum = 4
	StateEnumSessionEnding StateEnum = 5
	StateEnumFault StateEnum = 6
)

type SupplyStateEnum uint8

const (
	SupplyStateEnumDisabled SupplyStateEnum = 0
	SupplyStateEnumChargingEnabled SupplyStateEnum = 1
	SupplyStateEnumDischargingEnabled SupplyStateEnum = 2
	SupplyStateEnumDisabledError SupplyStateEnum = 3
	SupplyStateEnumDisabledDiagnostics SupplyStateEnum = 4
	SupplyStateEnumEnabled SupplyStateEnum = 5
)

type TargetDayOfWeekBitmap uint8

const (
	TargetDayOfWeekBitmapSunday TargetDayOfWeekBitmap = 0x1
	TargetDayOfWeekBitmapMonday TargetDayOfWeekBitmap = 0x2
	TargetDayOfWeekBitmapTuesday TargetDayOfWeekBitmap = 0x4
	TargetDayOfWeekBitmapWednesday TargetDayOfWeekBitmap = 0x8
	TargetDayOfWeekBitmapThursday TargetDayOfWeekBitmap = 0x10
	TargetDayOfWeekBitmapFriday TargetDayOfWeekBitmap = 0x20
	TargetDayOfWeekBitmapSaturday TargetDayOfWeekBitmap = 0x40
)



type ChargingTargetSchedule struct {
	DayOfWeekForSequence TargetDayOfWeekBitmap // Tag 0
	ChargingTargets []ChargingTarget // Tag 1
}

func (s *ChargingTargetSchedule) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: DayOfWeekForSequence Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.DayOfWeekForSequence)
    
	// Field: ChargingTargets Tag: 1
    if len(s.ChargingTargets) > 0 {
        
        list := make(tlv.StructArray, 0, len(s.ChargingTargets))
        for _, v := range s.ChargingTargets {
            list = append(list, v.Encode())
        }
        st[tlv.ContextTag(1)] = list
        
    }
	return st
}

func (s *ChargingTargetSchedule) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := TargetDayOfWeekBitmap(v)
s.DayOfWeekForSequence = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
            
            if list, ok := val.(tlv.StructArray); ok {
                 for _, item := range list {
                    var newItem ChargingTarget
                    if err := newItem.Decode(item); err != nil { return err }
                    s.ChargingTargets = append(s.ChargingTargets, newItem)
                 }
            }
            
        
	}

    return nil
}

type ChargingTarget struct {
	TargetTimeMinutesPastMidnight uint16 // Tag 0
	TargetSoC dm.Percent // Tag 1
	AddedEnergy dm.EnergyMWh // Tag 2
}

func (s *ChargingTarget) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: TargetTimeMinutesPastMidnight Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.TargetTimeMinutesPastMidnight)
    
	// Field: TargetSoC Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.TargetSoC)
    
	// Field: AddedEnergy Tag: 2
    
        st[tlv.ContextTag(2)] = int64(s.AddedEnergy)
    
	return st
}

func (s *ChargingTarget) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.TargetTimeMinutesPastMidnight = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.Percent(v)
s.TargetSoC = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := dm.EnergyMWh(v)
s.AddedEnergy = casted
}
        
        
	}

    return nil
}

