// Code generated by data_gen.go. DO NOT EDIT.

package ps

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type BatApprovedChemistryEnum uint8

const (
	BatApprovedChemistryEnumUnspecified BatApprovedChemistryEnum = 0
	BatApprovedChemistryEnumAlkaline BatApprovedChemistryEnum = 1
	BatApprovedChemistryEnumLithiumCarbonFluoride BatApprovedChemistryEnum = 2
	BatApprovedChemistryEnumLithiumChromiumOxide BatApprovedChemistryEnum = 3
	BatApprovedChemistryEnumLithiumCopperOxide BatApprovedChemistryEnum = 4
	BatApprovedChemistryEnumLithiumIronDisulfide BatApprovedChemistryEnum = 5
	BatApprovedChemistryEnumLithiumManganeseDioxide BatApprovedChemistryEnum = 6
	BatApprovedChemistryEnumLithiumThionylChloride BatApprovedChemistryEnum = 7
	BatApprovedChemistryEnumMagnesium BatApprovedChemistryEnum = 8
	BatApprovedChemistryEnumMercuryOxide BatApprovedChemistryEnum = 9
	BatApprovedChemistryEnumNickelOxyhydride BatApprovedChemistryEnum = 10
	BatApprovedChemistryEnumSilverOxide BatApprovedChemistryEnum = 11
	BatApprovedChemistryEnumZincAir BatApprovedChemistryEnum = 12
	BatApprovedChemistryEnumZincCarbon BatApprovedChemistryEnum = 13
	BatApprovedChemistryEnumZincChloride BatApprovedChemistryEnum = 14
	BatApprovedChemistryEnumZincManganeseDioxide BatApprovedChemistryEnum = 15
	BatApprovedChemistryEnumLeadAcid BatApprovedChemistryEnum = 16
	BatApprovedChemistryEnumLithiumCobaltOxide BatApprovedChemistryEnum = 17
	BatApprovedChemistryEnumLithiumIon BatApprovedChemistryEnum = 18
	BatApprovedChemistryEnumLithiumIonPolymer BatApprovedChemistryEnum = 19
	BatApprovedChemistryEnumLithiumIronPhosphate BatApprovedChemistryEnum = 20
	BatApprovedChemistryEnumLithiumSulfur BatApprovedChemistryEnum = 21
	BatApprovedChemistryEnumLithiumTitanate BatApprovedChemistryEnum = 22
	BatApprovedChemistryEnumNickelCadmium BatApprovedChemistryEnum = 23
	BatApprovedChemistryEnumNickelHydrogen BatApprovedChemistryEnum = 24
	BatApprovedChemistryEnumNickelIron BatApprovedChemistryEnum = 25
	BatApprovedChemistryEnumNickelMetalHydride BatApprovedChemistryEnum = 26
	BatApprovedChemistryEnumNickelZinc BatApprovedChemistryEnum = 27
	BatApprovedChemistryEnumSilverZinc BatApprovedChemistryEnum = 28
	BatApprovedChemistryEnumSodiumIon BatApprovedChemistryEnum = 29
	BatApprovedChemistryEnumSodiumSulfur BatApprovedChemistryEnum = 30
	BatApprovedChemistryEnumZincBromide BatApprovedChemistryEnum = 31
	BatApprovedChemistryEnumZincCerium BatApprovedChemistryEnum = 32
)

type BatChargeFaultEnum uint8

const (
	BatChargeFaultEnumUnspecified BatChargeFaultEnum = 0
	BatChargeFaultEnumAmbientTooHot BatChargeFaultEnum = 1
	BatChargeFaultEnumAmbientTooCold BatChargeFaultEnum = 2
	BatChargeFaultEnumBatteryTooHot BatChargeFaultEnum = 3
	BatChargeFaultEnumBatteryTooCold BatChargeFaultEnum = 4
	BatChargeFaultEnumBatteryAbsent BatChargeFaultEnum = 5
	BatChargeFaultEnumBatteryOverVoltage BatChargeFaultEnum = 6
	BatChargeFaultEnumBatteryUnderVoltage BatChargeFaultEnum = 7
	BatChargeFaultEnumChargerOverVoltage BatChargeFaultEnum = 8
	BatChargeFaultEnumChargerUnderVoltage BatChargeFaultEnum = 9
	BatChargeFaultEnumSafetyTimeout BatChargeFaultEnum = 10
)

type BatChargeLevelEnum uint8

const (
	BatChargeLevelEnumOK BatChargeLevelEnum = 0
	BatChargeLevelEnumWarning BatChargeLevelEnum = 1
	BatChargeLevelEnumCritical BatChargeLevelEnum = 2
)

type BatChargeStateEnum uint8

const (
	BatChargeStateEnumUnknown BatChargeStateEnum = 0
	BatChargeStateEnumIsCharging BatChargeStateEnum = 1
	BatChargeStateEnumIsAtFullCharge BatChargeStateEnum = 2
	BatChargeStateEnumIsNotCharging BatChargeStateEnum = 3
)

type BatCommonDesignationEnum uint8

const (
	BatCommonDesignationEnumUnspecified BatCommonDesignationEnum = 0
	BatCommonDesignationEnumAAA BatCommonDesignationEnum = 1
	BatCommonDesignationEnumAA BatCommonDesignationEnum = 2
	BatCommonDesignationEnumC BatCommonDesignationEnum = 3
	BatCommonDesignationEnumD BatCommonDesignationEnum = 4
	BatCommonDesignationEnum4v5 BatCommonDesignationEnum = 5
	BatCommonDesignationEnum6v0 BatCommonDesignationEnum = 6
	BatCommonDesignationEnum9v0 BatCommonDesignationEnum = 7
	BatCommonDesignationEnum1_2AA BatCommonDesignationEnum = 8
	BatCommonDesignationEnumAAAA BatCommonDesignationEnum = 9
	BatCommonDesignationEnumA BatCommonDesignationEnum = 10
	BatCommonDesignationEnumB BatCommonDesignationEnum = 11
	BatCommonDesignationEnumF BatCommonDesignationEnum = 12
	BatCommonDesignationEnumN BatCommonDesignationEnum = 13
	BatCommonDesignationEnumNo6 BatCommonDesignationEnum = 14
	BatCommonDesignationEnumSubC BatCommonDesignationEnum = 15
	BatCommonDesignationEnumA23 BatCommonDesignationEnum = 16
	BatCommonDesignationEnumA27 BatCommonDesignationEnum = 17
	BatCommonDesignationEnumBA5800 BatCommonDesignationEnum = 18
	BatCommonDesignationEnumDuplex BatCommonDesignationEnum = 19
	BatCommonDesignationEnum4SR44 BatCommonDesignationEnum = 20
	BatCommonDesignationEnum523 BatCommonDesignationEnum = 21
	BatCommonDesignationEnum531 BatCommonDesignationEnum = 22
	BatCommonDesignationEnum15v0 BatCommonDesignationEnum = 23
	BatCommonDesignationEnum22v5 BatCommonDesignationEnum = 24
	BatCommonDesignationEnum30v0 BatCommonDesignationEnum = 25
	BatCommonDesignationEnum45v0 BatCommonDesignationEnum = 26
	BatCommonDesignationEnum67v5 BatCommonDesignationEnum = 27
	BatCommonDesignationEnumJ BatCommonDesignationEnum = 28
	BatCommonDesignationEnumCR123A BatCommonDesignationEnum = 29
	BatCommonDesignationEnumCR2 BatCommonDesignationEnum = 30
	BatCommonDesignationEnum2CR5 BatCommonDesignationEnum = 31
	BatCommonDesignationEnumCR_P2 BatCommonDesignationEnum = 32
	BatCommonDesignationEnumCR_V3 BatCommonDesignationEnum = 33
	BatCommonDesignationEnumSR41 BatCommonDesignationEnum = 34
	BatCommonDesignationEnumSR43 BatCommonDesignationEnum = 35
	BatCommonDesignationEnumSR44 BatCommonDesignationEnum = 36
	BatCommonDesignationEnumSR45 BatCommonDesignationEnum = 37
	BatCommonDesignationEnumSR48 BatCommonDesignationEnum = 38
	BatCommonDesignationEnumSR54 BatCommonDesignationEnum = 39
	BatCommonDesignationEnumSR55 BatCommonDesignationEnum = 40
	BatCommonDesignationEnumSR57 BatCommonDesignationEnum = 41
	BatCommonDesignationEnumSR58 BatCommonDesignationEnum = 42
	BatCommonDesignationEnumSR59 BatCommonDesignationEnum = 43
	BatCommonDesignationEnumSR60 BatCommonDesignationEnum = 44
	BatCommonDesignationEnumSR63 BatCommonDesignationEnum = 45
	BatCommonDesignationEnumSR64 BatCommonDesignationEnum = 46
	BatCommonDesignationEnumSR65 BatCommonDesignationEnum = 47
	BatCommonDesignationEnumSR66 BatCommonDesignationEnum = 48
	BatCommonDesignationEnumSR67 BatCommonDesignationEnum = 49
	BatCommonDesignationEnumSR68 BatCommonDesignationEnum = 50
	BatCommonDesignationEnumSR69 BatCommonDesignationEnum = 51
	BatCommonDesignationEnumSR516 BatCommonDesignationEnum = 52
	BatCommonDesignationEnumSR731 BatCommonDesignationEnum = 53
	BatCommonDesignationEnumSR712 BatCommonDesignationEnum = 54
	BatCommonDesignationEnumLR932 BatCommonDesignationEnum = 55
	BatCommonDesignationEnumA5 BatCommonDesignationEnum = 56
	BatCommonDesignationEnumA10 BatCommonDesignationEnum = 57
	BatCommonDesignationEnumA13 BatCommonDesignationEnum = 58
	BatCommonDesignationEnumA312 BatCommonDesignationEnum = 59
	BatCommonDesignationEnumA675 BatCommonDesignationEnum = 60
	BatCommonDesignationEnumAC41E BatCommonDesignationEnum = 61
	BatCommonDesignationEnum10180 BatCommonDesignationEnum = 62
	BatCommonDesignationEnum10280 BatCommonDesignationEnum = 63
	BatCommonDesignationEnum10440 BatCommonDesignationEnum = 64
	BatCommonDesignationEnum14250 BatCommonDesignationEnum = 65
	BatCommonDesignationEnum14430 BatCommonDesignationEnum = 66
	BatCommonDesignationEnum14500 BatCommonDesignationEnum = 67
	BatCommonDesignationEnum14650 BatCommonDesignationEnum = 68
	BatCommonDesignationEnum15270 BatCommonDesignationEnum = 69
	BatCommonDesignationEnum16340 BatCommonDesignationEnum = 70
	BatCommonDesignationEnumRCR123A BatCommonDesignationEnum = 71
	BatCommonDesignationEnum17500 BatCommonDesignationEnum = 72
	BatCommonDesignationEnum17670 BatCommonDesignationEnum = 73
	BatCommonDesignationEnum18350 BatCommonDesignationEnum = 74
	BatCommonDesignationEnum18500 BatCommonDesignationEnum = 75
	BatCommonDesignationEnum18650 BatCommonDesignationEnum = 76
	BatCommonDesignationEnum19670 BatCommonDesignationEnum = 77
	BatCommonDesignationEnum25500 BatCommonDesignationEnum = 78
	BatCommonDesignationEnum26650 BatCommonDesignationEnum = 79
	BatCommonDesignationEnum32600 BatCommonDesignationEnum = 80
)

type BatFaultEnum uint8

const (
	BatFaultEnumUnspecified BatFaultEnum = 0
	BatFaultEnumOverTemp BatFaultEnum = 1
	BatFaultEnumUnderTemp BatFaultEnum = 2
)

type BatReplaceabilityEnum uint8

const (
	BatReplaceabilityEnumUnspecified BatReplaceabilityEnum = 0
	BatReplaceabilityEnumNotReplaceable BatReplaceabilityEnum = 1
	BatReplaceabilityEnumUserReplaceable BatReplaceabilityEnum = 2
	BatReplaceabilityEnumFactoryReplaceable BatReplaceabilityEnum = 3
)

type PowerSourceStatusEnum uint8

const (
	PowerSourceStatusEnumUnspecified PowerSourceStatusEnum = 0
	PowerSourceStatusEnumActive PowerSourceStatusEnum = 1
	PowerSourceStatusEnumStandby PowerSourceStatusEnum = 2
	PowerSourceStatusEnumUnavailable PowerSourceStatusEnum = 3
)

type WiredCurrentTypeEnum uint8

const (
	WiredCurrentTypeEnumAC WiredCurrentTypeEnum = 0
	WiredCurrentTypeEnumDC WiredCurrentTypeEnum = 1
)

type WiredFaultEnum uint8

const (
	WiredFaultEnumUnspecified WiredFaultEnum = 0
	WiredFaultEnumOverVoltage WiredFaultEnum = 1
	WiredFaultEnumUnderVoltage WiredFaultEnum = 2
)



