// Code generated by data_gen.go. DO NOT EDIT.

package otccm

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ModeTag uint16

const (
	ModeTagAuto ModeTag = 0x00
	ModeTagQuick ModeTag = 0x01
	ModeTagQuiet ModeTag = 0x02
	ModeTagLowNoise ModeTag = 0x03
	ModeTagLowEnergy ModeTag = 0x04
	ModeTagVacation ModeTag = 0x05
	ModeTagMin ModeTag = 0x06
	ModeTagMax ModeTag = 0x07
	ModeTagNight ModeTag = 0x08
	ModeTagDay ModeTag = 0x09
	ModeTagBake ModeTag = 0x4000
	ModeTagConvection ModeTag = 0x4001
	ModeTagGrill ModeTag = 0x4002
	ModeTagRoast ModeTag = 0x4003
	ModeTagClean ModeTag = 0x4004
	ModeTagConvection_Bake ModeTag = 0x4005
	ModeTagConvection_Roast ModeTag = 0x4006
	ModeTagWarming ModeTag = 0x4007
	ModeTagProofing ModeTag = 0x4008
	ModeTagSteam ModeTag = 0x4009
)



