// Code generated by data_gen.go. DO NOT EDIT.

package rvcopstate

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ErrorStateEnum uint8

const (
	ErrorStateEnumNoError ErrorStateEnum = 0x00
	ErrorStateEnumUnableToStartOrResume ErrorStateEnum = 0x01
	ErrorStateEnumUnableToCompleteOperation ErrorStateEnum = 0x02
	ErrorStateEnumCommandInvalidInState ErrorStateEnum = 0x03
	ErrorStateEnumFailedToFindChargingDock ErrorStateEnum = 0x40
	ErrorStateEnumStuck ErrorStateEnum = 0x41
	ErrorStateEnumDustBinMissing ErrorStateEnum = 0x42
	ErrorStateEnumDustBinFull ErrorStateEnum = 0x43
	ErrorStateEnumWaterTankEmpty ErrorStateEnum = 0x44
	ErrorStateEnumWaterTankMissing ErrorStateEnum = 0x45
	ErrorStateEnumWaterTankLidOpen ErrorStateEnum = 0x46
	ErrorStateEnumMopCleaningPadMissing ErrorStateEnum = 0x47
	ErrorStateEnumLowBattery ErrorStateEnum = 0x48
	ErrorStateEnumCannotReachTargetArea ErrorStateEnum = 0x49
	ErrorStateEnumDirtyWaterTankFull ErrorStateEnum = 0x4A
	ErrorStateEnumDirtyWaterTankMissing ErrorStateEnum = 0x4B
	ErrorStateEnumWheelsJammed ErrorStateEnum = 0x4C
	ErrorStateEnumBrushJammed ErrorStateEnum = 0x4D
	ErrorStateEnumNavigationSensorObscured ErrorStateEnum = 0x4E
)

type OperationalStateEnum uint8

const (
	OperationalStateEnumStopped OperationalStateEnum = 0x00
	OperationalStateEnumRunning OperationalStateEnum = 0x01
	OperationalStateEnumPaused OperationalStateEnum = 0x02
	OperationalStateEnumError OperationalStateEnum = 0x03
	OperationalStateEnumSeekingCharger OperationalStateEnum = 0x40
	OperationalStateEnumCharging OperationalStateEnum = 0x41
	OperationalStateEnumDocked OperationalStateEnum = 0x42
	OperationalStateEnumEmptyingDustBin OperationalStateEnum = 0x43
	OperationalStateEnumCleaningMop OperationalStateEnum = 0x44
	OperationalStateEnumFillingWaterTank OperationalStateEnum = 0x45
	OperationalStateEnumUpdatingMaps OperationalStateEnum = 0x46
)



