// Code generated by data_gen.go. DO NOT EDIT.

package dryerctrl

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type DrynessLevelEnum uint8

const (
	DrynessLevelEnumLow DrynessLevelEnum = 0
	DrynessLevelEnumNormal DrynessLevelEnum = 1
	DrynessLevelEnumExtra DrynessLevelEnum = 2
	DrynessLevelEnumMax DrynessLevelEnum = 3
)



