// Code generated by data_gen.go. DO NOT EDIT.

package valcc

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type StatusCodeEnum uint8

const (
	StatusCodeEnumFailureDueToFault StatusCodeEnum = 0x02
)

type ValveStateEnum uint8

const (
	ValveStateEnumClosed ValveStateEnum = 0
	ValveStateEnumOpen ValveStateEnum = 1
	ValveStateEnumTransitioning ValveStateEnum = 2
)

type ValveFaultBitmap uint8

const (
	ValveFaultBitmapGeneralFault ValveFaultBitmap = 0x1
	ValveFaultBitmapBlocked ValveFaultBitmap = 0x2
	ValveFaultBitmapLeaking ValveFaultBitmap = 0x4
	ValveFaultBitmapNotConnected ValveFaultBitmap = 0x8
	ValveFaultBitmapShortCircuit ValveFaultBitmap = 0x10
	ValveFaultBitmapCurrentExceeded ValveFaultBitmap = 0x20
)



