// Code generated by data_gen.go. DO NOT EDIT.

package fan

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type AirflowDirectionEnum uint8

const (
	AirflowDirectionEnumForward AirflowDirectionEnum = 0
	AirflowDirectionEnumReverse AirflowDirectionEnum = 1
)

type FanModeEnum uint8

const (
	FanModeEnumOff FanModeEnum = 0
	FanModeEnumLow FanModeEnum = 1
	FanModeEnumMedium FanModeEnum = 2
	FanModeEnumHigh FanModeEnum = 3
	FanModeEnumOn FanModeEnum = 4
	FanModeEnumAuto FanModeEnum = 5
	FanModeEnumSmart FanModeEnum = 6
)

type FanModeSequenceEnum uint8

const (
	FanModeSequenceEnumOffLowMedHigh FanModeSequenceEnum = 0
	FanModeSequenceEnumOffLowHigh FanModeSequenceEnum = 1
	FanModeSequenceEnumOffLowMedHighAuto FanModeSequenceEnum = 2
	FanModeSequenceEnumOffLowHighAuto FanModeSequenceEnum = 3
	FanModeSequenceEnumOffHighAuto FanModeSequenceEnum = 4
	FanModeSequenceEnumOffHigh FanModeSequenceEnum = 5
)

type StepDirectionEnum uint8

const (
	StepDirectionEnumIncrease StepDirectionEnum = 0
	StepDirectionEnumDecrease StepDirectionEnum = 1
)

type RockBitmap uint8

const (
	RockBitmapRockLeftRight RockBitmap = 0x1
	RockBitmapRockUpDown RockBitmap = 0x2
	RockBitmapRockRound RockBitmap = 0x4
)

type WindBitmap uint8

const (
	WindBitmapSleepWind WindBitmap = 0x1
	WindBitmapNaturalWind WindBitmap = 0x2
)



