// Code generated by data_gen.go. DO NOT EDIT.

package wncv

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type EndProductTypeEnum uint8

const (
	EndProductTypeEnumRollerShade EndProductTypeEnum = 0
	EndProductTypeEnumRomanShade EndProductTypeEnum = 1
	EndProductTypeEnumBalloonShade EndProductTypeEnum = 2
	EndProductTypeEnumWovenWood EndProductTypeEnum = 3
	EndProductTypeEnumPleatedShade EndProductTypeEnum = 4
	EndProductTypeEnumCellularShade EndProductTypeEnum = 5
	EndProductTypeEnumLayeredShade EndProductTypeEnum = 6
	EndProductTypeEnumLayeredShade2D EndProductTypeEnum = 7
	EndProductTypeEnumSheerShade EndProductTypeEnum = 8
	EndProductTypeEnumTiltOnlyInteriorBlind EndProductTypeEnum = 9
	EndProductTypeEnumInteriorBlind EndProductTypeEnum = 10
	EndProductTypeEnumVerticalBlindStripCurtain EndProductTypeEnum = 11
	EndProductTypeEnumInteriorVenetianBlind EndProductTypeEnum = 12
	EndProductTypeEnumExteriorVenetianBlind EndProductTypeEnum = 13
	EndProductTypeEnumLateralLeftCurtain EndProductTypeEnum = 14
	EndProductTypeEnumLateralRightCurtain EndProductTypeEnum = 15
	EndProductTypeEnumCentralCurtain EndProductTypeEnum = 16
	EndProductTypeEnumRollerShutter EndProductTypeEnum = 17
	EndProductTypeEnumExteriorVerticalScreen EndProductTypeEnum = 18
	EndProductTypeEnumAwningTerracePatio EndProductTypeEnum = 19
	EndProductTypeEnumAwningVerticalScreen EndProductTypeEnum = 20
	EndProductTypeEnumTiltOnlyPergola EndProductTypeEnum = 21
	EndProductTypeEnumSwingingShutter EndProductTypeEnum = 22
	EndProductTypeEnumSlidingShutter EndProductTypeEnum = 23
	EndProductTypeEnumUnknown EndProductTypeEnum = 255
)

type TypeEnum uint8

const (
	TypeEnumRollerShade TypeEnum = 0
	TypeEnumRollerShade2Motor TypeEnum = 1
	TypeEnumRollerShadeExterior TypeEnum = 2
	TypeEnumRollerShadeExterior2Motor TypeEnum = 3
	TypeEnumDrapery TypeEnum = 4
	TypeEnumAwning TypeEnum = 5
	TypeEnumShutter TypeEnum = 6
	TypeEnumTiltBlindTiltOnly TypeEnum = 7
	TypeEnumTiltBlindLiftAndTilt TypeEnum = 8
	TypeEnumProjectorScreen TypeEnum = 9
	TypeEnumUnknown TypeEnum = 255
)

type ConfigStatusBitmap uint8

const (
	ConfigStatusBitmapOperational ConfigStatusBitmap = 0x1
	ConfigStatusBitmapOnlineReserved ConfigStatusBitmap = 0x2
	ConfigStatusBitmapLiftMovementReversed ConfigStatusBitmap = 0x4
	ConfigStatusBitmapLiftPositionAware ConfigStatusBitmap = 0x8
	ConfigStatusBitmapTiltPositionAware ConfigStatusBitmap = 0x10
	ConfigStatusBitmapLiftEncoderControlled ConfigStatusBitmap = 0x20
	ConfigStatusBitmapTiltEncoderControlled ConfigStatusBitmap = 0x40
)

type ModeBitmap uint8

const (
	ModeBitmapMotorDirectionReversed ModeBitmap = 0x1
	ModeBitmapCalibrationMode ModeBitmap = 0x2
	ModeBitmapMaintenanceMode ModeBitmap = 0x4
	ModeBitmapLedFeedback ModeBitmap = 0x8
)

type OperationalStatusBitmap uint8

const (
	OperationalStatusBitmapGlobal OperationalStatusBitmap = 0x1
	OperationalStatusBitmapLift OperationalStatusBitmap = 0x1
	OperationalStatusBitmapTilt OperationalStatusBitmap = 0x1
)

type SafetyStatusBitmap uint16

const (
	SafetyStatusBitmapRemoteLockout SafetyStatusBitmap = 0x1
	SafetyStatusBitmapTamperDetection SafetyStatusBitmap = 0x2
	SafetyStatusBitmapFailedCommunication SafetyStatusBitmap = 0x4
	SafetyStatusBitmapPositionFailure SafetyStatusBitmap = 0x8
	SafetyStatusBitmapThermalProtection SafetyStatusBitmap = 0x10
	SafetyStatusBitmapObstacleDetected SafetyStatusBitmap = 0x20
	SafetyStatusBitmapPower SafetyStatusBitmap = 0x40
	SafetyStatusBitmapStopInput SafetyStatusBitmap = 0x80
	SafetyStatusBitmapMotorJammed SafetyStatusBitmap = 0x100
	SafetyStatusBitmapHardwareFailure SafetyStatusBitmap = 0x200
	SafetyStatusBitmapManualOperation SafetyStatusBitmap = 0x400
	SafetyStatusBitmapProtection SafetyStatusBitmap = 0x800
)



