// Code generated by data_gen.go. DO NOT EDIT.

package icdm

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ClientTypeEnum uint8

const (
	ClientTypeEnumPermanent ClientTypeEnum = 0
	ClientTypeEnumEphemeral ClientTypeEnum = 1
)

type OperatingModeEnum uint8

const (
	OperatingModeEnumSIT OperatingModeEnum = 0
	OperatingModeEnumLIT OperatingModeEnum = 1
)

type UserActiveModeTriggerBitmap uint32

const (
	UserActiveModeTriggerBitmapPowerCycle UserActiveModeTriggerBitmap = 0x1
	UserActiveModeTriggerBitmapSettingsMenu UserActiveModeTriggerBitmap = 0x2
	UserActiveModeTriggerBitmapCustomInstruction UserActiveModeTriggerBitmap = 0x4
	UserActiveModeTriggerBitmapDeviceManual UserActiveModeTriggerBitmap = 0x8
	UserActiveModeTriggerBitmapActuateSensor UserActiveModeTriggerBitmap = 0x10
	UserActiveModeTriggerBitmapActuateSensorSeconds UserActiveModeTriggerBitmap = 0x20
	UserActiveModeTriggerBitmapActuateSensorTimes UserActiveModeTriggerBitmap = 0x40
	UserActiveModeTriggerBitmapActuateSensorLightsBlink UserActiveModeTriggerBitmap = 0x80
	UserActiveModeTriggerBitmapResetButton UserActiveModeTriggerBitmap = 0x100
	UserActiveModeTriggerBitmapResetButtonLightsBlink UserActiveModeTriggerBitmap = 0x200
	UserActiveModeTriggerBitmapResetButtonSeconds UserActiveModeTriggerBitmap = 0x400
	UserActiveModeTriggerBitmapResetButtonTimes UserActiveModeTriggerBitmap = 0x800
	UserActiveModeTriggerBitmapSetupButton UserActiveModeTriggerBitmap = 0x1000
	UserActiveModeTriggerBitmapSetupButtonSeconds UserActiveModeTriggerBitmap = 0x2000
	UserActiveModeTriggerBitmapSetupButtonLightsBlink UserActiveModeTriggerBitmap = 0x4000
	UserActiveModeTriggerBitmapSetupButtonTimes UserActiveModeTriggerBitmap = 0x8000
	UserActiveModeTriggerBitmapAppDefinedButton UserActiveModeTriggerBitmap = 0x10000
)



type MonitoringRegistration struct {
	CheckInNodeID dm.NodeID // Tag 1
	MonitoredSubject dm.SubjectID // Tag 2
	ClientType ClientTypeEnum // Tag 4
}

func (s *MonitoringRegistration) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: CheckInNodeID Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.CheckInNodeID)
    
	// Field: MonitoredSubject Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.MonitoredSubject)
    
	// Field: ClientType Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.ClientType)
    
	return st
}

func (s *MonitoringRegistration) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.NodeID(v)
s.CheckInNodeID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.SubjectID(v)
s.MonitoredSubject = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ClientTypeEnum(v)
s.ClientType = casted
}
        
        
	}

    return nil
}

