// Code generated by data_gen.go. DO NOT EDIT.

package jfpki

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ICACResponseStatusEnum uint8

const (
	ICACResponseStatusEnumOK ICACResponseStatusEnum = 0
	ICACResponseStatusEnumInvalidPublicKey ICACResponseStatusEnum = 1
	ICACResponseStatusEnumInvalidICAC ICACResponseStatusEnum = 2
)

type StatusCodeEnum uint8

const (
	StatusCodeEnumBusy StatusCodeEnum = 0x02
	StatusCodeEnumPAKEParameterError StatusCodeEnum = 0x03
	StatusCodeEnumWindowNotOpen StatusCodeEnum = 0x04
	StatusCodeEnumVIDNotVerified StatusCodeEnum = 0x05
	StatusCodeEnumInvalidAdministratorFabricIndex StatusCodeEnum = 0x06
)

type TransferAnchorResponseStatusEnum uint8

const (
	TransferAnchorResponseStatusEnumOK TransferAnchorResponseStatusEnum = 0
	TransferAnchorResponseStatusEnumTransferAnchorStatusDatastoreBusy TransferAnchorResponseStatusEnum = 1
	TransferAnchorResponseStatusEnumTransferAnchorStatusNoUserConsent TransferAnchorResponseStatusEnum = 2
)



