// Code generated by data_gen.go. DO NOT EDIT.

package act

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ActionErrorEnum uint8

const (
	ActionErrorEnumUnknown ActionErrorEnum = 0
	ActionErrorEnumInterrupted ActionErrorEnum = 1
)

type ActionStateEnum uint8

const (
	ActionStateEnumInactive ActionStateEnum = 0
	ActionStateEnumActive ActionStateEnum = 1
	ActionStateEnumPaused ActionStateEnum = 2
	ActionStateEnumDisabled ActionStateEnum = 3
)

type ActionTypeEnum uint8

const (
	ActionTypeEnumOther ActionTypeEnum = 0
	ActionTypeEnumScene ActionTypeEnum = 1
	ActionTypeEnumSequence ActionTypeEnum = 2
	ActionTypeEnumAutomation ActionTypeEnum = 3
	ActionTypeEnumException ActionTypeEnum = 4
	ActionTypeEnumNotification ActionTypeEnum = 5
	ActionTypeEnumAlarm ActionTypeEnum = 6
)

type EndpointListTypeEnum uint8

const (
	EndpointListTypeEnumOther EndpointListTypeEnum = 0
	EndpointListTypeEnumRoom EndpointListTypeEnum = 1
	EndpointListTypeEnumZone EndpointListTypeEnum = 2
)

type CommandBits uint16

const (
	CommandBitsInstantAction CommandBits = 0x1
	CommandBitsInstantActionWithTransition CommandBits = 0x2
	CommandBitsStartAction CommandBits = 0x4
	CommandBitsStartActionWithDuration CommandBits = 0x8
	CommandBitsStopAction CommandBits = 0x10
	CommandBitsPauseAction CommandBits = 0x20
	CommandBitsPauseActionWithDuration CommandBits = 0x40
	CommandBitsResumeAction CommandBits = 0x80
	CommandBitsEnableAction CommandBits = 0x100
	CommandBitsEnableActionWithDuration CommandBits = 0x200
	CommandBitsDisableAction CommandBits = 0x400
	CommandBitsDisableActionWithDuration CommandBits = 0x800
)



type Action struct {
	ActionID uint16 // Tag 0
	Name string // Tag 1
	Type ActionTypeEnum // Tag 2
	EndpointListID uint16 // Tag 3
	SupportedCommands CommandBits // Tag 4
	State ActionStateEnum // Tag 5
}

func (s *Action) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ActionID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.ActionID)
    
	// Field: Name Tag: 1
    
        st[tlv.ContextTag(1)] = (s.Name)
    
	// Field: Type Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.Type)
    
	// Field: EndpointListID Tag: 3
    
        st[tlv.ContextTag(3)] = uint64(s.EndpointListID)
    
	// Field: SupportedCommands Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.SupportedCommands)
    
	// Field: State Tag: 5
    
        st[tlv.ContextTag(5)] = uint64(s.State)
    
	return st
}

func (s *Action) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.ActionID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ActionTypeEnum(v)
s.Type = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.EndpointListID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := CommandBits(v)
s.SupportedCommands = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ActionStateEnum(v)
s.State = casted
}
        
        
	}

    return nil
}

type EndpointList struct {
	EndpointListID uint16 // Tag 0
	Name string // Tag 1
	Type EndpointListTypeEnum // Tag 2
	Endpoints []dm.EndpointID // Tag 3
}

func (s *EndpointList) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: EndpointListID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.EndpointListID)
    
	// Field: Name Tag: 1
    
        st[tlv.ContextTag(1)] = (s.Name)
    
	// Field: Type Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.Type)
    
	// Field: Endpoints Tag: 3
    if len(s.Endpoints) > 0 {
        
        list := make(tlv.UintArray, 0, len(s.Endpoints))
        for _, v := range s.Endpoints {
            list = append(list, uint64(v))
        }
        st[tlv.ContextTag(3)] = list
        
    }
	return st
}

func (s *EndpointList) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.EndpointListID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := EndpointListTypeEnum(v)
s.Type = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
            
            if arr, ok := val.(tlv.UintArray); ok {
                 for _, item := range arr {
                     s.Endpoints = append(s.Endpoints, dm.EndpointID(item))
                 }
            }
            
        
	}

    return nil
}

