// Code generated by data_gen.go. DO NOT EDIT.

package tstat

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ACCapacityFormatEnum uint8

const (
	ACCapacityFormatEnumBTUh ACCapacityFormatEnum = 0
)

type ACCompressorTypeEnum uint8

const (
	ACCompressorTypeEnumUnknown ACCompressorTypeEnum = 0
	ACCompressorTypeEnumT1 ACCompressorTypeEnum = 1
	ACCompressorTypeEnumT2 ACCompressorTypeEnum = 2
	ACCompressorTypeEnumT3 ACCompressorTypeEnum = 3
)

type ACLouverPositionEnum uint8

const (
	ACLouverPositionEnumClosed ACLouverPositionEnum = 1
	ACLouverPositionEnumOpen ACLouverPositionEnum = 2
	ACLouverPositionEnumQuarter ACLouverPositionEnum = 3
	ACLouverPositionEnumHalf ACLouverPositionEnum = 4
	ACLouverPositionEnumThreeQuarters ACLouverPositionEnum = 5
)

type ACRefrigerantTypeEnum uint8

const (
	ACRefrigerantTypeEnumUnknown ACRefrigerantTypeEnum = 0
	ACRefrigerantTypeEnumR22 ACRefrigerantTypeEnum = 1
	ACRefrigerantTypeEnumR410a ACRefrigerantTypeEnum = 2
	ACRefrigerantTypeEnumR407c ACRefrigerantTypeEnum = 3
)

type ACTypeEnum uint8

const (
	ACTypeEnumUnknown ACTypeEnum = 0
	ACTypeEnumCoolingFixed ACTypeEnum = 1
	ACTypeEnumHeatPumpFixed ACTypeEnum = 2
	ACTypeEnumCoolingInverter ACTypeEnum = 3
	ACTypeEnumHeatPumpInverter ACTypeEnum = 4
)

type ControlSequenceOfOperationEnum uint8

const (
	ControlSequenceOfOperationEnumCoolingOnly ControlSequenceOfOperationEnum = 0
	ControlSequenceOfOperationEnumCoolingWithReheat ControlSequenceOfOperationEnum = 1
	ControlSequenceOfOperationEnumHeatingOnly ControlSequenceOfOperationEnum = 2
	ControlSequenceOfOperationEnumHeatingWithReheat ControlSequenceOfOperationEnum = 3
	ControlSequenceOfOperationEnumCoolingAndHeating ControlSequenceOfOperationEnum = 4
	ControlSequenceOfOperationEnumCoolingAndHeatingWithReheat ControlSequenceOfOperationEnum = 5
)

type PresetScenarioEnum uint8

const (
	PresetScenarioEnumOccupied PresetScenarioEnum = 1
	PresetScenarioEnumUnoccupied PresetScenarioEnum = 2
	PresetScenarioEnumSleep PresetScenarioEnum = 3
	PresetScenarioEnumWake PresetScenarioEnum = 4
	PresetScenarioEnumVacation PresetScenarioEnum = 5
	PresetScenarioEnumGoingToSleep PresetScenarioEnum = 6
	PresetScenarioEnumUserDefined PresetScenarioEnum = 254
)

type SetpointChangeSourceEnum uint8

const (
	SetpointChangeSourceEnumManual SetpointChangeSourceEnum = 0
	SetpointChangeSourceEnumSchedule SetpointChangeSourceEnum = 1
	SetpointChangeSourceEnumExternal SetpointChangeSourceEnum = 2
)

type SetpointRaiseLowerModeEnum uint8

const (
	SetpointRaiseLowerModeEnumHeat SetpointRaiseLowerModeEnum = 0
	SetpointRaiseLowerModeEnumCool SetpointRaiseLowerModeEnum = 1
	SetpointRaiseLowerModeEnumBoth SetpointRaiseLowerModeEnum = 2
)

type StartOfWeekEnum uint8

const (
	StartOfWeekEnumSunday StartOfWeekEnum = 0
	StartOfWeekEnumMonday StartOfWeekEnum = 1
	StartOfWeekEnumTuesday StartOfWeekEnum = 2
	StartOfWeekEnumWednesday StartOfWeekEnum = 3
	StartOfWeekEnumThursday StartOfWeekEnum = 4
	StartOfWeekEnumFriday StartOfWeekEnum = 5
	StartOfWeekEnumSaturday StartOfWeekEnum = 6
)

type SystemModeEnum uint8

const (
	SystemModeEnumOff SystemModeEnum = 0
	SystemModeEnumAuto SystemModeEnum = 1
	SystemModeEnumCool SystemModeEnum = 3
	SystemModeEnumHeat SystemModeEnum = 4
	SystemModeEnumEmergencyHeat SystemModeEnum = 5
	SystemModeEnumPrecooling SystemModeEnum = 6
	SystemModeEnumFanOnly SystemModeEnum = 7
	SystemModeEnumDry SystemModeEnum = 8
	SystemModeEnumSleep SystemModeEnum = 9
)

type TemperatureSetpointHoldEnum uint8

const (
	TemperatureSetpointHoldEnumSetpointHoldOff TemperatureSetpointHoldEnum = 0
	TemperatureSetpointHoldEnumSetpointHoldOn TemperatureSetpointHoldEnum = 1
)

type ThermostatRunningModeEnum uint8

const (
	ThermostatRunningModeEnumOff ThermostatRunningModeEnum = 0
	ThermostatRunningModeEnumCool ThermostatRunningModeEnum = 3
	ThermostatRunningModeEnumHeat ThermostatRunningModeEnum = 4
)

type ACErrorCodeBitmap uint8

const (
	ACErrorCodeBitmapCompressorFail ACErrorCodeBitmap = 0x1
	ACErrorCodeBitmapRoomSensorFail ACErrorCodeBitmap = 0x2
	ACErrorCodeBitmapOutdoorSensorFail ACErrorCodeBitmap = 0x4
	ACErrorCodeBitmapCoilSensorFail ACErrorCodeBitmap = 0x8
	ACErrorCodeBitmapFanFail ACErrorCodeBitmap = 0x10
)

type HVACSystemTypeBitmap uint8

const (
	HVACSystemTypeBitmapCoolingStage HVACSystemTypeBitmap = 0x1
	HVACSystemTypeBitmapHeatingStage HVACSystemTypeBitmap = 0x1
	HVACSystemTypeBitmapHeatingIsHeatPump HVACSystemTypeBitmap = 0x10
	HVACSystemTypeBitmapHeatingUsesFuel HVACSystemTypeBitmap = 0x20
)

type OccupancyBitmap uint8

const (
	OccupancyBitmapOccupied OccupancyBitmap = 0x1
)

type PresetTypeFeaturesBitmap uint8

const (
	PresetTypeFeaturesBitmapAutomatic PresetTypeFeaturesBitmap = 0x1
	PresetTypeFeaturesBitmapSupportsNames PresetTypeFeaturesBitmap = 0x2
)

type ProgrammingOperationModeBitmap uint8

const (
	ProgrammingOperationModeBitmapScheduleActive ProgrammingOperationModeBitmap = 0x1
	ProgrammingOperationModeBitmapAutoRecovery ProgrammingOperationModeBitmap = 0x2
	ProgrammingOperationModeBitmapEconomy ProgrammingOperationModeBitmap = 0x4
)

type RelayStateBitmap uint8

const (
	RelayStateBitmapHeat RelayStateBitmap = 0x1
	RelayStateBitmapCool RelayStateBitmap = 0x2
	RelayStateBitmapFan RelayStateBitmap = 0x4
	RelayStateBitmapHeatStage2 RelayStateBitmap = 0x8
	RelayStateBitmapCoolStage2 RelayStateBitmap = 0x10
	RelayStateBitmapFanStage2 RelayStateBitmap = 0x20
	RelayStateBitmapFanStage3 RelayStateBitmap = 0x40
)

type RemoteSensingBitmap uint8

const (
	RemoteSensingBitmapLocalTemperature RemoteSensingBitmap = 0x1
	RemoteSensingBitmapOutdoorTemperature RemoteSensingBitmap = 0x2
	RemoteSensingBitmapOccupancy RemoteSensingBitmap = 0x4
)

type ScheduleDayOfWeekBitmap uint8

const (
	ScheduleDayOfWeekBitmapSunday ScheduleDayOfWeekBitmap = 0x1
	ScheduleDayOfWeekBitmapMonday ScheduleDayOfWeekBitmap = 0x2
	ScheduleDayOfWeekBitmapTuesday ScheduleDayOfWeekBitmap = 0x4
	ScheduleDayOfWeekBitmapWednesday ScheduleDayOfWeekBitmap = 0x8
	ScheduleDayOfWeekBitmapThursday ScheduleDayOfWeekBitmap = 0x10
	ScheduleDayOfWeekBitmapFriday ScheduleDayOfWeekBitmap = 0x20
	ScheduleDayOfWeekBitmapSaturday ScheduleDayOfWeekBitmap = 0x40
	ScheduleDayOfWeekBitmapAway ScheduleDayOfWeekBitmap = 0x80
)

type ScheduleModeBitmap uint8

const (
	ScheduleModeBitmapHeatSetpointPresent ScheduleModeBitmap = 0x1
	ScheduleModeBitmapCoolSetpointPresent ScheduleModeBitmap = 0x2
)

type ScheduleTypeFeaturesBitmap uint8

const (
	ScheduleTypeFeaturesBitmapSupportsPresets ScheduleTypeFeaturesBitmap = 0x1
	ScheduleTypeFeaturesBitmapSupportsSetpoints ScheduleTypeFeaturesBitmap = 0x2
	ScheduleTypeFeaturesBitmapSupportsNames ScheduleTypeFeaturesBitmap = 0x4
	ScheduleTypeFeaturesBitmapSupportsOff ScheduleTypeFeaturesBitmap = 0x8
)



type Preset struct {
	PresetHandle *[]byte // Tag 0
	PresetScenario PresetScenarioEnum // Tag 1
	Name *string // Tag 2
	CoolingSetpoint dm.Temperature // Tag 3
	HeatingSetpoint dm.Temperature // Tag 4
	BuiltIn *bool // Tag 5
}

func (s *Preset) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: PresetHandle Tag: 0
    if s.PresetHandle != nil {
        st[tlv.ContextTag(0)] = []byte(*s.PresetHandle)
    }
	// Field: PresetScenario Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.PresetScenario)
    
	// Field: Name Tag: 2
    if s.Name != nil {
        st[tlv.ContextTag(2)] = (*s.Name)
    }
	// Field: CoolingSetpoint Tag: 3
    
        st[tlv.ContextTag(3)] = int64(s.CoolingSetpoint)
    
	// Field: HeatingSetpoint Tag: 4
    
        st[tlv.ContextTag(4)] = int64(s.HeatingSetpoint)
    
	// Field: BuiltIn Tag: 5
    if s.BuiltIn != nil {
        st[tlv.ContextTag(5)] = (*s.BuiltIn)
    }
	return st
}

func (s *Preset) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.PresetHandle = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := PresetScenarioEnum(v)
s.PresetScenario = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := dm.Temperature(v)
s.CoolingSetpoint = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := dm.Temperature(v)
s.HeatingSetpoint = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.BuiltIn = &v
}
        
        
	}

    return nil
}

type PresetType struct {
	PresetScenario PresetScenarioEnum // Tag 0
	NumberOfPresets uint8 // Tag 1
	PresetTypeFeatures PresetTypeFeaturesBitmap // Tag 2
}

func (s *PresetType) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: PresetScenario Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.PresetScenario)
    
	// Field: NumberOfPresets Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.NumberOfPresets)
    
	// Field: PresetTypeFeatures Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.PresetTypeFeatures)
    
	return st
}

func (s *PresetType) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := PresetScenarioEnum(v)
s.PresetScenario = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.NumberOfPresets = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := PresetTypeFeaturesBitmap(v)
s.PresetTypeFeatures = casted
}
        
        
	}

    return nil
}

type Schedule struct {
	ScheduleHandle *[]byte // Tag 0
	SystemMode SystemModeEnum // Tag 1
	Name *string // Tag 2
	PresetHandle *[]byte // Tag 3
	Transitions []ScheduleTransition // Tag 4
	BuiltIn *bool // Tag 5
}

func (s *Schedule) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ScheduleHandle Tag: 0
    if s.ScheduleHandle != nil {
        st[tlv.ContextTag(0)] = []byte(*s.ScheduleHandle)
    }
	// Field: SystemMode Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.SystemMode)
    
	// Field: Name Tag: 2
    if s.Name != nil {
        st[tlv.ContextTag(2)] = (*s.Name)
    }
	// Field: PresetHandle Tag: 3
    if s.PresetHandle != nil {
        st[tlv.ContextTag(3)] = []byte(*s.PresetHandle)
    }
	// Field: Transitions Tag: 4
    if len(s.Transitions) > 0 {
        
        list := make(tlv.StructArray, 0, len(s.Transitions))
        for _, v := range s.Transitions {
            list = append(list, v.Encode())
        }
        st[tlv.ContextTag(4)] = list
        
    }
	// Field: BuiltIn Tag: 5
    if s.BuiltIn != nil {
        st[tlv.ContextTag(5)] = (*s.BuiltIn)
    }
	return st
}

func (s *Schedule) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.ScheduleHandle = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := SystemModeEnum(v)
s.SystemMode = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.PresetHandle = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
            
            if list, ok := val.(tlv.StructArray); ok {
                 for _, item := range list {
                    var newItem ScheduleTransition
                    if err := newItem.Decode(item); err != nil { return err }
                    s.Transitions = append(s.Transitions, newItem)
                 }
            }
            
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.BuiltIn = &v
}
        
        
	}

    return nil
}

type ScheduleTransition struct {
	DayOfWeek ScheduleDayOfWeekBitmap // Tag 0
	TransitionTime uint16 // Tag 1
	PresetHandle *[]byte // Tag 2
	SystemMode *SystemModeEnum // Tag 3
	CoolingSetpoint *dm.Temperature // Tag 4
	HeatingSetpoint *dm.Temperature // Tag 5
}

func (s *ScheduleTransition) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: DayOfWeek Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.DayOfWeek)
    
	// Field: TransitionTime Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.TransitionTime)
    
	// Field: PresetHandle Tag: 2
    if s.PresetHandle != nil {
        st[tlv.ContextTag(2)] = []byte(*s.PresetHandle)
    }
	// Field: SystemMode Tag: 3
    if s.SystemMode != nil {
        st[tlv.ContextTag(3)] = uint64(*s.SystemMode)
    }
	// Field: CoolingSetpoint Tag: 4
    if s.CoolingSetpoint != nil {
        st[tlv.ContextTag(4)] = int64(*s.CoolingSetpoint)
    }
	// Field: HeatingSetpoint Tag: 5
    if s.HeatingSetpoint != nil {
        st[tlv.ContextTag(5)] = int64(*s.HeatingSetpoint)
    }
	return st
}

func (s *ScheduleTransition) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ScheduleDayOfWeekBitmap(v)
s.DayOfWeek = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.TransitionTime = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.([]byte); ok {
s.PresetHandle = &v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := SystemModeEnum(v)
s.SystemMode = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := dm.Temperature(v)
s.CoolingSetpoint = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := dm.Temperature(v)
s.HeatingSetpoint = &casted
}
        
        
	}

    return nil
}

type ScheduleType struct {
	SystemMode SystemModeEnum // Tag 0
	NumberOfSchedules uint8 // Tag 1
	ScheduleTypeFeatures ScheduleTypeFeaturesBitmap // Tag 2
}

func (s *ScheduleType) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: SystemMode Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.SystemMode)
    
	// Field: NumberOfSchedules Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.NumberOfSchedules)
    
	// Field: ScheduleTypeFeatures Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.ScheduleTypeFeatures)
    
	return st
}

func (s *ScheduleType) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := SystemModeEnum(v)
s.SystemMode = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.NumberOfSchedules = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ScheduleTypeFeaturesBitmap(v)
s.ScheduleTypeFeatures = casted
}
        
        
	}

    return nil
}

type WeeklyScheduleTransition struct {
	TransitionTime uint16 // Tag 0
	HeatSetpoint *dm.Temperature // Tag 1
	CoolSetpoint *dm.Temperature // Tag 2
}

func (s *WeeklyScheduleTransition) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: TransitionTime Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.TransitionTime)
    
	// Field: HeatSetpoint Tag: 1
    if s.HeatSetpoint != nil {
        st[tlv.ContextTag(1)] = int64(*s.HeatSetpoint)
    }
	// Field: CoolSetpoint Tag: 2
    if s.CoolSetpoint != nil {
        st[tlv.ContextTag(2)] = int64(*s.CoolSetpoint)
    }
	return st
}

func (s *WeeklyScheduleTransition) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.TransitionTime = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := dm.Temperature(v)
s.HeatSetpoint = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := dm.Temperature(v)
s.CoolSetpoint = &casted
}
        
        
	}

    return nil
}

