// Code generated by data_gen.go. DO NOT EDIT.

package sear

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type OperationalStatusEnum uint8

const (
	OperationalStatusEnumPending OperationalStatusEnum = 0x00
	OperationalStatusEnumOperating OperationalStatusEnum = 0x01
	OperationalStatusEnumSkipped OperationalStatusEnum = 0x02
	OperationalStatusEnumCompleted OperationalStatusEnum = 0x03
)

type SelectAreasStatus uint8

const (
	SelectAreasStatusSuccess SelectAreasStatus = 0x00
	SelectAreasStatusUnsupportedArea SelectAreasStatus = 0x01
	SelectAreasStatusInvalidInMode SelectAreasStatus = 0x02
	SelectAreasStatusInvalidSet SelectAreasStatus = 0x03
)

type SkipAreaStatus uint8

const (
	SkipAreaStatusSuccess SkipAreaStatus = 0x00
	SkipAreaStatusInvalidAreaList SkipAreaStatus = 0x01
	SkipAreaStatusInvalidInMode SkipAreaStatus = 0x02
	SkipAreaStatusInvalidSkippedArea SkipAreaStatus = 0x03
)



type AreaInfo struct {
	LocationInfo *dm.LocationDescriptor // Tag 0
	LandmarkInfo *LandmarkInfo // Tag 1
}

func (s *AreaInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: LocationInfo Tag: 0
    if s.LocationInfo != nil {
        st[tlv.ContextTag(0)] = s.LocationInfo.Encode()
        
    }
	// Field: LandmarkInfo Tag: 1
    if s.LandmarkInfo != nil {
        st[tlv.ContextTag(1)] = s.LandmarkInfo.Encode()
        
    }
	return st
}

func (s *AreaInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        s.LocationInfo = &dm.LocationDescriptor{}
        if err := s.LocationInfo.Decode(val); err != nil { return err }
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        s.LandmarkInfo = &LandmarkInfo{}
        if err := s.LandmarkInfo.Decode(val); err != nil { return err }
        
        
	}

    return nil
}

type Area struct {
	AreaID uint32 // Tag 0
	MapID *uint32 // Tag 1
	AreaInfo AreaInfo // Tag 2
}

func (s *Area) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: AreaID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.AreaID)
    
	// Field: MapID Tag: 1
    if s.MapID != nil {
        st[tlv.ContextTag(1)] = uint64(*s.MapID)
    }
	// Field: AreaInfo Tag: 2
    
        st[tlv.ContextTag(2)] = s.AreaInfo.Encode()
        
    
	return st
}

func (s *Area) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.AreaID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.MapID = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        if err := s.AreaInfo.Decode(val); err != nil { return err }
        
        
	}

    return nil
}

type LandmarkInfo struct {
	LandmarkTag dm.Tag // Tag 0
	RelativePositionTag *dm.Tag // Tag 1
}

func (s *LandmarkInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: LandmarkTag Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.LandmarkTag)
    
	// Field: RelativePositionTag Tag: 1
    if s.RelativePositionTag != nil {
        st[tlv.ContextTag(1)] = uint64(*s.RelativePositionTag)
    }
	return st
}

func (s *LandmarkInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.Tag(v)
s.LandmarkTag = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.Tag(v)
s.RelativePositionTag = &casted
}
        
        
	}

    return nil
}

type Map struct {
	MapID uint32 // Tag 0
	Name string // Tag 1
}

func (s *Map) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: MapID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.MapID)
    
	// Field: Name Tag: 1
    
        st[tlv.ContextTag(1)] = (s.Name)
    
	return st
}

func (s *Map) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.MapID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Name = v
}
        
        
	}

    return nil
}

type Progress struct {
	AreaID uint32 // Tag 0
	Status OperationalStatusEnum // Tag 1
	TotalOperationalTime *dm.ElapsedS // Tag 2
	EstimatedTime *dm.ElapsedS // Tag 3
}

func (s *Progress) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: AreaID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.AreaID)
    
	// Field: Status Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Status)
    
	// Field: TotalOperationalTime Tag: 2
    if s.TotalOperationalTime != nil {
        st[tlv.ContextTag(2)] = uint64(*s.TotalOperationalTime)
    }
	// Field: EstimatedTime Tag: 3
    if s.EstimatedTime != nil {
        st[tlv.ContextTag(3)] = uint64(*s.EstimatedTime)
    }
	return st
}

func (s *Progress) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.AreaID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := OperationalStatusEnum(v)
s.Status = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.ElapsedS(v)
s.TotalOperationalTime = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.ElapsedS(v)
s.EstimatedTime = &casted
}
        
        
	}

    return nil
}

