// Code generated by data_gen.go. DO NOT EDIT.

package dgeth

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type PHYRateEnum uint8

const (
	PHYRateEnumRate10M PHYRateEnum = 0
	PHYRateEnumRate100M PHYRateEnum = 1
	PHYRateEnumRate1G PHYRateEnum = 2
	PHYRateEnumRate2_5G PHYRateEnum = 3
	PHYRateEnumRate5G PHYRateEnum = 4
	PHYRateEnumRate10G PHYRateEnum = 5
	PHYRateEnumRate40G PHYRateEnum = 6
	PHYRateEnumRate100G PHYRateEnum = 7
	PHYRateEnumRate200G PHYRateEnum = 8
	PHYRateEnumRate400G PHYRateEnum = 9
)



