// Code generated by data_gen.go. DO NOT EDIT.

package mod

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()







type ModeOption struct {
	Label string // Tag 0
	Mode uint8 // Tag 1
	SemanticTags []SemanticTag // Tag 2
}

func (s *ModeOption) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Label Tag: 0
    
        st[tlv.ContextTag(0)] = (s.Label)
    
	// Field: Mode Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Mode)
    
	// Field: SemanticTags Tag: 2
    if len(s.SemanticTags) > 0 {
        
        list := make(tlv.StructArray, 0, len(s.SemanticTags))
        for _, v := range s.SemanticTags {
            list = append(list, v.Encode())
        }
        st[tlv.ContextTag(2)] = list
        
    }
	return st
}

func (s *ModeOption) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(string); ok {
s.Label = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.Mode = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
            
            if list, ok := val.(tlv.StructArray); ok {
                 for _, item := range list {
                    var newItem SemanticTag
                    if err := newItem.Decode(item); err != nil { return err }
                    s.SemanticTags = append(s.SemanticTags, newItem)
                 }
            }
            
        
	}

    return nil
}

type SemanticTag struct {
	MfgCode dm.VendorID // Tag 0
	Value dm.Enum16 // Tag 1
}

func (s *SemanticTag) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: MfgCode Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.MfgCode)
    
	// Field: Value Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Value)
    
	return st
}

func (s *SemanticTag) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.VendorID(v)
s.MfgCode = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.Enum16(v)
s.Value = casted
}
        
        
	}

    return nil
}

