// Code generated by data_gen.go. DO NOT EDIT.

package eevsem

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ModeTag uint16

const (
	ModeTagAuto ModeTag = 0x00
	ModeTagQuick ModeTag = 0x01
	ModeTagQuiet ModeTag = 0x02
	ModeTagLowNoise ModeTag = 0x03
	ModeTagLowEnergy ModeTag = 0x04
	ModeTagVacation ModeTag = 0x05
	ModeTagMin ModeTag = 0x06
	ModeTagMax ModeTag = 0x07
	ModeTagNight ModeTag = 0x08
	ModeTagDay ModeTag = 0x09
	ModeTagManual ModeTag = 0x4000
	ModeTagTimeOfUse ModeTag = 0x4001
	ModeTagSolarCharging ModeTag = 0x4002
	ModeTagV2X ModeTag = 0x4003
)



