// Code generated by data_gen.go. DO NOT EDIT.

package i

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type EffectIdentifierEnum uint8

const (
	EffectIdentifierEnumBlink EffectIdentifierEnum = 0x00
	EffectIdentifierEnumBreathe EffectIdentifierEnum = 0x01
	EffectIdentifierEnumOkay EffectIdentifierEnum = 0x02
	EffectIdentifierEnumChannelChange EffectIdentifierEnum = 0x0B
	EffectIdentifierEnumFinishEffect EffectIdentifierEnum = 0xFE
	EffectIdentifierEnumStopEffect EffectIdentifierEnum = 0xFF
)

type EffectVariantEnum uint8

const (
	EffectVariantEnumDefault EffectVariantEnum = 0x00
)

type IdentifyTypeEnum uint8

const (
	IdentifyTypeEnumNone IdentifyTypeEnum = 0x00
	IdentifyTypeEnumLightOutput IdentifyTypeEnum = 0x01
	IdentifyTypeEnumVisibleIndicator IdentifyTypeEnum = 0x02
	IdentifyTypeEnumAudibleBeep IdentifyTypeEnum = 0x03
	IdentifyTypeEnumDisplay IdentifyTypeEnum = 0x04
	IdentifyTypeEnumActuator IdentifyTypeEnum = 0x05
)



