// Code generated by data_gen.go. DO NOT EDIT.

package binfo

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ColorEnum uint8

const (
	ColorEnumBlack ColorEnum = 0
	ColorEnumNavy ColorEnum = 1
	ColorEnumGreen ColorEnum = 2
	ColorEnumTeal ColorEnum = 3
	ColorEnumMaroon ColorEnum = 4
	ColorEnumPurple ColorEnum = 5
	ColorEnumOlive ColorEnum = 6
	ColorEnumGray ColorEnum = 7
	ColorEnumBlue ColorEnum = 8
	ColorEnumLime ColorEnum = 9
	ColorEnumAqua ColorEnum = 10
	ColorEnumRed ColorEnum = 11
	ColorEnumFuchsia ColorEnum = 12
	ColorEnumYellow ColorEnum = 13
	ColorEnumWhite ColorEnum = 14
	ColorEnumNickel ColorEnum = 15
	ColorEnumChrome ColorEnum = 16
	ColorEnumBrass ColorEnum = 17
	ColorEnumCopper ColorEnum = 18
	ColorEnumSilver ColorEnum = 19
	ColorEnumGold ColorEnum = 20
)

type ProductFinishEnum uint8

const (
	ProductFinishEnumOther ProductFinishEnum = 0
	ProductFinishEnumMatte ProductFinishEnum = 1
	ProductFinishEnumSatin ProductFinishEnum = 2
	ProductFinishEnumPolished ProductFinishEnum = 3
	ProductFinishEnumRugged ProductFinishEnum = 4
	ProductFinishEnumFabric ProductFinishEnum = 5
)



type CapabilityMinima struct {
	CaseSessionsPerFabric uint16 // Tag 0
	SubscriptionsPerFabric uint16 // Tag 1
}

func (s *CapabilityMinima) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: CaseSessionsPerFabric Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.CaseSessionsPerFabric)
    
	// Field: SubscriptionsPerFabric Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.SubscriptionsPerFabric)
    
	return st
}

func (s *CapabilityMinima) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.CaseSessionsPerFabric = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.SubscriptionsPerFabric = casted
}
        
        
	}

    return nil
}

type ProductAppearance struct {
	Finish ProductFinishEnum // Tag 0
	PrimaryColor *ColorEnum // Tag 1
}

func (s *ProductAppearance) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: Finish Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.Finish)
    
	// Field: PrimaryColor Tag: 1
    if s.PrimaryColor != nil {
        st[tlv.ContextTag(1)] = uint64(*s.PrimaryColor)
    }
	return st
}

func (s *ProductAppearance) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ProductFinishEnum(v)
s.Finish = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ColorEnum(v)
s.PrimaryColor = &casted
}
        
        
	}

    return nil
}

