// Code generated by data_gen.go. DO NOT EDIT.

package keypadinput

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type CecKeyCodeEnum uint8

const (
	CecKeyCodeEnumSelect CecKeyCodeEnum = 0x00
	CecKeyCodeEnumUp CecKeyCodeEnum = 0x01
	CecKeyCodeEnumDown CecKeyCodeEnum = 0x02
	CecKeyCodeEnumLeft CecKeyCodeEnum = 0x03
	CecKeyCodeEnumRight CecKeyCodeEnum = 0x04
	CecKeyCodeEnumRightUp CecKeyCodeEnum = 0x05
	CecKeyCodeEnumRightDown CecKeyCodeEnum = 0x06
	CecKeyCodeEnumLeftUp CecKeyCodeEnum = 0x07
	CecKeyCodeEnumLeftDown CecKeyCodeEnum = 0x08
	CecKeyCodeEnumRootMenu CecKeyCodeEnum = 0x09
	CecKeyCodeEnumSetupMenu CecKeyCodeEnum = 0x0A
	CecKeyCodeEnumContentsMenu CecKeyCodeEnum = 0x0B
	CecKeyCodeEnumFavoriteMenu CecKeyCodeEnum = 0x0C
	CecKeyCodeEnumExit CecKeyCodeEnum = 0x0D
	CecKeyCodeEnumMediaTopMenu CecKeyCodeEnum = 0x10
	CecKeyCodeEnumMediaContextSensitiveMenu CecKeyCodeEnum = 0x11
	CecKeyCodeEnumNumberEntryMode CecKeyCodeEnum = 0x1D
	CecKeyCodeEnumNumber11 CecKeyCodeEnum = 0x1E
	CecKeyCodeEnumNumber12 CecKeyCodeEnum = 0x1F
	CecKeyCodeEnumNumber0OrNumber10 CecKeyCodeEnum = 0x20
	CecKeyCodeEnumNumbers1 CecKeyCodeEnum = 0x21
	CecKeyCodeEnumNumbers2 CecKeyCodeEnum = 0x22
	CecKeyCodeEnumNumbers3 CecKeyCodeEnum = 0x23
	CecKeyCodeEnumNumbers4 CecKeyCodeEnum = 0x24
	CecKeyCodeEnumNumbers5 CecKeyCodeEnum = 0x25
	CecKeyCodeEnumNumbers6 CecKeyCodeEnum = 0x26
	CecKeyCodeEnumNumbers7 CecKeyCodeEnum = 0x27
	CecKeyCodeEnumNumbers8 CecKeyCodeEnum = 0x28
	CecKeyCodeEnumNumbers9 CecKeyCodeEnum = 0x29
	CecKeyCodeEnumDot CecKeyCodeEnum = 0x2A
	CecKeyCodeEnumEnter CecKeyCodeEnum = 0x2B
	CecKeyCodeEnumClear CecKeyCodeEnum = 0x2C
	CecKeyCodeEnumNextFavorite CecKeyCodeEnum = 0x2F
	CecKeyCodeEnumChannelUp CecKeyCodeEnum = 0x30
	CecKeyCodeEnumChannelDown CecKeyCodeEnum = 0x31
	CecKeyCodeEnumPreviousChannel CecKeyCodeEnum = 0x32
	CecKeyCodeEnumSoundSelect CecKeyCodeEnum = 0x33
	CecKeyCodeEnumInputSelect CecKeyCodeEnum = 0x34
	CecKeyCodeEnumDisplayInformation CecKeyCodeEnum = 0x35
	CecKeyCodeEnumHelp CecKeyCodeEnum = 0x36
	CecKeyCodeEnumPageUp CecKeyCodeEnum = 0x37
	CecKeyCodeEnumPageDown CecKeyCodeEnum = 0x38
	CecKeyCodeEnumPower CecKeyCodeEnum = 0x40
	CecKeyCodeEnumVolumeUp CecKeyCodeEnum = 0x41
	CecKeyCodeEnumVolumeDown CecKeyCodeEnum = 0x42
	CecKeyCodeEnumMute CecKeyCodeEnum = 0x43
	CecKeyCodeEnumPlay CecKeyCodeEnum = 0x44
	CecKeyCodeEnumStop CecKeyCodeEnum = 0x45
	CecKeyCodeEnumPause CecKeyCodeEnum = 0x46
	CecKeyCodeEnumRecord CecKeyCodeEnum = 0x47
	CecKeyCodeEnumRewind CecKeyCodeEnum = 0x48
	CecKeyCodeEnumFastForward CecKeyCodeEnum = 0x49
	CecKeyCodeEnumEject CecKeyCodeEnum = 0x4A
	CecKeyCodeEnumForward CecKeyCodeEnum = 0x4B
	CecKeyCodeEnumBackward CecKeyCodeEnum = 0x4C
	CecKeyCodeEnumStopRecord CecKeyCodeEnum = 0x4D
	CecKeyCodeEnumPauseRecord CecKeyCodeEnum = 0x4E
	CecKeyCodeEnumReserved CecKeyCodeEnum = 0x4F
	CecKeyCodeEnumAngle CecKeyCodeEnum = 0x50
	CecKeyCodeEnumSubPicture CecKeyCodeEnum = 0x51
	CecKeyCodeEnumVideoOnDemand CecKeyCodeEnum = 0x52
	CecKeyCodeEnumElectronicProgramGuide CecKeyCodeEnum = 0x53
	CecKeyCodeEnumTimerProgramming CecKeyCodeEnum = 0x54
	CecKeyCodeEnumInitialConfiguration CecKeyCodeEnum = 0x55
	CecKeyCodeEnumSelectBroadcastType CecKeyCodeEnum = 0x56
	CecKeyCodeEnumSelectSoundPresentation CecKeyCodeEnum = 0x57
	CecKeyCodeEnumPlayFunction CecKeyCodeEnum = 0x60
	CecKeyCodeEnumPausePlayFunction CecKeyCodeEnum = 0x61
	CecKeyCodeEnumRecordFunction CecKeyCodeEnum = 0x62
	CecKeyCodeEnumPauseRecordFunction CecKeyCodeEnum = 0x63
	CecKeyCodeEnumStopFunction CecKeyCodeEnum = 0x64
	CecKeyCodeEnumMuteFunction CecKeyCodeEnum = 0x65
	CecKeyCodeEnumRestoreVolumeFunction CecKeyCodeEnum = 0x66
	CecKeyCodeEnumTuneFunction CecKeyCodeEnum = 0x67
	CecKeyCodeEnumSelectMediaFunction CecKeyCodeEnum = 0x68
	CecKeyCodeEnumSelectAvInputFunction CecKeyCodeEnum = 0x69
	CecKeyCodeEnumSelectAudioInputFunction CecKeyCodeEnum = 0x6A
	CecKeyCodeEnumPowerToggleFunction CecKeyCodeEnum = 0x6B
	CecKeyCodeEnumPowerOffFunction CecKeyCodeEnum = 0x6C
	CecKeyCodeEnumPowerOnFunction CecKeyCodeEnum = 0x6D
	CecKeyCodeEnumF1Blue CecKeyCodeEnum = 0x71
	CecKeyCodeEnumF2Red CecKeyCodeEnum = 0x72
	CecKeyCodeEnumF3Green CecKeyCodeEnum = 0x73
	CecKeyCodeEnumF4Yellow CecKeyCodeEnum = 0x74
	CecKeyCodeEnumF5 CecKeyCodeEnum = 0x75
	CecKeyCodeEnumData CecKeyCodeEnum = 0x76
)

type StatusEnum uint8

const (
	StatusEnumSuccess StatusEnum = 0
	StatusEnumUnsupportedKey StatusEnum = 1
	StatusEnumInvalidKeyInCurrentState StatusEnum = 2
)



