// Code generated by data_gen.go. DO NOT EDIT.

package drlk

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type AlarmCodeEnum uint8

const (
	AlarmCodeEnumLockJammed AlarmCodeEnum = 0
	AlarmCodeEnumLockFactoryReset AlarmCodeEnum = 1
	AlarmCodeEnumLockRadioPowerCycled AlarmCodeEnum = 3
	AlarmCodeEnumWrongCodeEntryLimit AlarmCodeEnum = 4
	AlarmCodeEnumFrontEsceutcheonRemoved AlarmCodeEnum = 5
	AlarmCodeEnumDoorForcedOpen AlarmCodeEnum = 6
	AlarmCodeEnumDoorAjar AlarmCodeEnum = 7
	AlarmCodeEnumForcedUser AlarmCodeEnum = 8
)

type CredentialRuleEnum uint8

const (
	CredentialRuleEnumSingle CredentialRuleEnum = 0
	CredentialRuleEnumDual CredentialRuleEnum = 1
	CredentialRuleEnumTri CredentialRuleEnum = 2
)

type CredentialTypeEnum uint8

const (
	CredentialTypeEnumProgrammingPIN CredentialTypeEnum = 0
	CredentialTypeEnumPIN CredentialTypeEnum = 1
	CredentialTypeEnumRFID CredentialTypeEnum = 2
	CredentialTypeEnumFingerprint CredentialTypeEnum = 3
	CredentialTypeEnumFingerVein CredentialTypeEnum = 4
	CredentialTypeEnumFace CredentialTypeEnum = 5
	CredentialTypeEnumAliroCredentialIssuerKey CredentialTypeEnum = 6
	CredentialTypeEnumAliroEvictableEndpointKey CredentialTypeEnum = 7
	CredentialTypeEnumAliroNonEvictableEndpointKey CredentialTypeEnum = 8
)

type DataOperationTypeEnum uint8

const (
	DataOperationTypeEnumAdd DataOperationTypeEnum = 0
	DataOperationTypeEnumClear DataOperationTypeEnum = 1
	DataOperationTypeEnumModify DataOperationTypeEnum = 2
)

type DoorStateEnum uint8

const (
	DoorStateEnumDoorOpen DoorStateEnum = 0
	DoorStateEnumDoorClosed DoorStateEnum = 1
	DoorStateEnumDoorJammed DoorStateEnum = 2
	DoorStateEnumDoorForcedOpen DoorStateEnum = 3
	DoorStateEnumDoorUnspecifiedError DoorStateEnum = 4
	DoorStateEnumDoorAjar DoorStateEnum = 5
)

type EventTypeEnum uint8

const (
	EventTypeEnumOperation EventTypeEnum = 0
	EventTypeEnumProgramming EventTypeEnum = 1
	EventTypeEnumAlarm EventTypeEnum = 2
)

type LEDSettingEnum uint8

const (
	LEDSettingEnumNoLEDSignal LEDSettingEnum = 0
	LEDSettingEnumNoLEDSignalAccessAllowed LEDSettingEnum = 1
	LEDSettingEnumLEDSignalAll LEDSettingEnum = 2
)

type LockDataTypeEnum uint8

const (
	LockDataTypeEnumUnspecified LockDataTypeEnum = 0
	LockDataTypeEnumProgrammingCode LockDataTypeEnum = 1
	LockDataTypeEnumUserIndex LockDataTypeEnum = 2
	LockDataTypeEnumWeekDaySchedule LockDataTypeEnum = 3
	LockDataTypeEnumYearDaySchedule LockDataTypeEnum = 4
	LockDataTypeEnumHolidaySchedule LockDataTypeEnum = 5
	LockDataTypeEnumPIN LockDataTypeEnum = 6
	LockDataTypeEnumRFID LockDataTypeEnum = 7
	LockDataTypeEnumFingerprint LockDataTypeEnum = 8
	LockDataTypeEnumFingerVein LockDataTypeEnum = 9
	LockDataTypeEnumFace LockDataTypeEnum = 10
	LockDataTypeEnumAliroCredentialIssuerKey LockDataTypeEnum = 11
	LockDataTypeEnumAliroEvictableEndpointKey LockDataTypeEnum = 12
	LockDataTypeEnumAliroNonEvictableEndpointKey LockDataTypeEnum = 13
)

type LockOperationTypeEnum uint8

const (
	LockOperationTypeEnumLock LockOperationTypeEnum = 0
	LockOperationTypeEnumUnlock LockOperationTypeEnum = 1
	LockOperationTypeEnumNonAccessUserEvent LockOperationTypeEnum = 2
	LockOperationTypeEnumForcedUserEvent LockOperationTypeEnum = 3
	LockOperationTypeEnumUnlatch LockOperationTypeEnum = 4
)

type LockStateEnum uint8

const (
	LockStateEnumNotFullyLocked LockStateEnum = 0
	LockStateEnumLocked LockStateEnum = 1
	LockStateEnumUnlocked LockStateEnum = 2
	LockStateEnumUnlatched LockStateEnum = 3
)

type LockTypeEnum uint8

const (
	LockTypeEnumDeadBolt LockTypeEnum = 0
	LockTypeEnumMagnetic LockTypeEnum = 1
	LockTypeEnumOther LockTypeEnum = 2
	LockTypeEnumMortise LockTypeEnum = 3
	LockTypeEnumRim LockTypeEnum = 4
	LockTypeEnumLatchBolt LockTypeEnum = 5
	LockTypeEnumCylindricalLock LockTypeEnum = 6
	LockTypeEnumTubularLock LockTypeEnum = 7
	LockTypeEnumInterconnectedLock LockTypeEnum = 8
	LockTypeEnumDeadLatch LockTypeEnum = 9
	LockTypeEnumDoorFurniture LockTypeEnum = 10
	LockTypeEnumEurocylinder LockTypeEnum = 11
)

type OperatingModeEnum uint8

const (
	OperatingModeEnumNormal OperatingModeEnum = 0
	OperatingModeEnumVacation OperatingModeEnum = 1
	OperatingModeEnumPrivacy OperatingModeEnum = 2
	OperatingModeEnumNoRemoteLockUnlock OperatingModeEnum = 3
	OperatingModeEnumPassage OperatingModeEnum = 4
)

type OperationErrorEnum uint8

const (
	OperationErrorEnumUnspecified OperationErrorEnum = 0
	OperationErrorEnumInvalidCredential OperationErrorEnum = 1
	OperationErrorEnumDisabledUserDenied OperationErrorEnum = 2
	OperationErrorEnumRestricted OperationErrorEnum = 3
	OperationErrorEnumInsufficientBattery OperationErrorEnum = 4
)

type OperationSourceEnum uint8

const (
	OperationSourceEnumUnspecified OperationSourceEnum = 0
	OperationSourceEnumManual OperationSourceEnum = 1
	OperationSourceEnumProprietaryRemote OperationSourceEnum = 2
	OperationSourceEnumKeypad OperationSourceEnum = 3
	OperationSourceEnumAuto OperationSourceEnum = 4
	OperationSourceEnumButton OperationSourceEnum = 5
	OperationSourceEnumSchedule OperationSourceEnum = 6
	OperationSourceEnumRemote OperationSourceEnum = 7
	OperationSourceEnumRFID OperationSourceEnum = 8
	OperationSourceEnumBiometric OperationSourceEnum = 9
	OperationSourceEnumAliro OperationSourceEnum = 10
)

type SoundVolumeEnum uint8

const (
	SoundVolumeEnumSilent SoundVolumeEnum = 0
	SoundVolumeEnumLow SoundVolumeEnum = 1
	SoundVolumeEnumHigh SoundVolumeEnum = 2
	SoundVolumeEnumMedium SoundVolumeEnum = 3
)

type StatusCodeEnum uint8

const (
	StatusCodeEnumDUPLICATE StatusCodeEnum = 0x02
	StatusCodeEnumOCCUPIED StatusCodeEnum = 0x03
)

type UserStatusEnum uint8

const (
	UserStatusEnumAvailable UserStatusEnum = 0
	UserStatusEnumOccupiedEnabled UserStatusEnum = 1
	UserStatusEnumOccupiedDisabled UserStatusEnum = 3
)

type UserTypeEnum uint8

const (
	UserTypeEnumUnrestrictedUser UserTypeEnum = 0
	UserTypeEnumYearDayScheduleUser UserTypeEnum = 1
	UserTypeEnumWeekDayScheduleUser UserTypeEnum = 2
	UserTypeEnumProgrammingUser UserTypeEnum = 3
	UserTypeEnumNonAccessUser UserTypeEnum = 4
	UserTypeEnumForcedUser UserTypeEnum = 5
	UserTypeEnumDisposableUser UserTypeEnum = 6
	UserTypeEnumExpiringUser UserTypeEnum = 7
	UserTypeEnumScheduleRestrictedUser UserTypeEnum = 8
	UserTypeEnumRemoteOnlyUser UserTypeEnum = 9
)

type AlarmMaskBitmap uint8

const (
	AlarmMaskBitmapLockJammed AlarmMaskBitmap = 0x1
	AlarmMaskBitmapLockFactoryReset AlarmMaskBitmap = 0x2
	AlarmMaskBitmapLockRadioPowerCycled AlarmMaskBitmap = 0x8
	AlarmMaskBitmapWrongCodeEntryLimit AlarmMaskBitmap = 0x10
	AlarmMaskBitmapFrontEscutcheonRemoved AlarmMaskBitmap = 0x20
	AlarmMaskBitmapDoorForcedOpen AlarmMaskBitmap = 0x40
)

type ConfigurationRegisterBitmap uint8

const (
	ConfigurationRegisterBitmapLocalProgramming ConfigurationRegisterBitmap = 0x1
	ConfigurationRegisterBitmapKeypadInterface ConfigurationRegisterBitmap = 0x2
	ConfigurationRegisterBitmapRemoteInterface ConfigurationRegisterBitmap = 0x4
	ConfigurationRegisterBitmapSoundVolume ConfigurationRegisterBitmap = 0x20
	ConfigurationRegisterBitmapAutoRelockTime ConfigurationRegisterBitmap = 0x40
	ConfigurationRegisterBitmapLEDSettings ConfigurationRegisterBitmap = 0x80
)

type CredentialRulesBitmap uint8

const (
	CredentialRulesBitmapSingle CredentialRulesBitmap = 0x1
	CredentialRulesBitmapDual CredentialRulesBitmap = 0x2
	CredentialRulesBitmapTri CredentialRulesBitmap = 0x4
)

type DaysMaskBitmap uint8

const (
	DaysMaskBitmapSunday DaysMaskBitmap = 0x1
	DaysMaskBitmapMonday DaysMaskBitmap = 0x2
	DaysMaskBitmapTuesday DaysMaskBitmap = 0x4
	DaysMaskBitmapWednesday DaysMaskBitmap = 0x8
	DaysMaskBitmapThursday DaysMaskBitmap = 0x10
	DaysMaskBitmapFriday DaysMaskBitmap = 0x20
	DaysMaskBitmapSaturday DaysMaskBitmap = 0x40
)

type LocalProgrammingFeaturesBitmap uint8

const (
	LocalProgrammingFeaturesBitmapAddUsersCredentialsSchedules LocalProgrammingFeaturesBitmap = 0x1
	LocalProgrammingFeaturesBitmapModifyUsersCredentialsSchedules LocalProgrammingFeaturesBitmap = 0x2
	LocalProgrammingFeaturesBitmapClearUsersCredentialsSchedules LocalProgrammingFeaturesBitmap = 0x4
	LocalProgrammingFeaturesBitmapAdjustSettings LocalProgrammingFeaturesBitmap = 0x8
)

type OperatingModesBitmap uint8

const (
	OperatingModesBitmapNormal OperatingModesBitmap = 0x1
	OperatingModesBitmapVacation OperatingModesBitmap = 0x2
	OperatingModesBitmapPrivacy OperatingModesBitmap = 0x4
	OperatingModesBitmapNoRemoteLockUnlock OperatingModesBitmap = 0x8
	OperatingModesBitmapPassage OperatingModesBitmap = 0x10
)



type Credential struct {
	CredentialType CredentialTypeEnum // Tag 0
	CredentialIndex uint16 // Tag 1
}

func (s *Credential) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: CredentialType Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.CredentialType)
    
	// Field: CredentialIndex Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.CredentialIndex)
    
	return st
}

func (s *Credential) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := CredentialTypeEnum(v)
s.CredentialType = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.CredentialIndex = casted
}
        
        
	}

    return nil
}

