// Code generated by data_gen.go. DO NOT EDIT.

package otar

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type AnnouncementReasonEnum uint8

const (
	AnnouncementReasonEnumSimpleAnnouncement AnnouncementReasonEnum = 0
	AnnouncementReasonEnumUpdateAvailable AnnouncementReasonEnum = 1
	AnnouncementReasonEnumUrgentUpdateAvailable AnnouncementReasonEnum = 2
)

type ChangeReasonEnum uint8

const (
	ChangeReasonEnumUnknown ChangeReasonEnum = 0
	ChangeReasonEnumSuccess ChangeReasonEnum = 1
	ChangeReasonEnumFailure ChangeReasonEnum = 2
	ChangeReasonEnumTimeOut ChangeReasonEnum = 3
	ChangeReasonEnumDelayByProvider ChangeReasonEnum = 4
)

type UpdateStateEnum uint8

const (
	UpdateStateEnumUnknown UpdateStateEnum = 0
	UpdateStateEnumIdle UpdateStateEnum = 1
	UpdateStateEnumQuerying UpdateStateEnum = 2
	UpdateStateEnumDelayedOnQuery UpdateStateEnum = 3
	UpdateStateEnumDownloading UpdateStateEnum = 4
	UpdateStateEnumApplying UpdateStateEnum = 5
	UpdateStateEnumDelayedOnApply UpdateStateEnum = 6
	UpdateStateEnumRollingBack UpdateStateEnum = 7
	UpdateStateEnumDelayedOnUserConsent UpdateStateEnum = 8
)



type ProviderLocation struct {
	ProviderNodeID dm.NodeID // Tag 1
	Endpoint dm.EndpointID // Tag 2
}

func (s *ProviderLocation) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ProviderNodeID Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.ProviderNodeID)
    
	// Field: Endpoint Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.Endpoint)
    
	return st
}

func (s *ProviderLocation) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.NodeID(v)
s.ProviderNodeID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.EndpointID(v)
s.Endpoint = casted
}
        
        
	}

    return nil
}

