// Code generated by data_gen.go. DO NOT EDIT.

package repm

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type ChangeIndicationEnum uint8

const (
	ChangeIndicationEnumOK ChangeIndicationEnum = 0
	ChangeIndicationEnumWarning ChangeIndicationEnum = 1
	ChangeIndicationEnumCritical ChangeIndicationEnum = 2
)

type DegradationDirectionEnum uint8

const (
	DegradationDirectionEnumUp DegradationDirectionEnum = 0
	DegradationDirectionEnumDown DegradationDirectionEnum = 1
)

type ProductIdentifierTypeEnum uint8

const (
	ProductIdentifierTypeEnumUPC ProductIdentifierTypeEnum = 0
	ProductIdentifierTypeEnumGTIN_8 ProductIdentifierTypeEnum = 1
	ProductIdentifierTypeEnumEAN ProductIdentifierTypeEnum = 2
	ProductIdentifierTypeEnumGTIN_14 ProductIdentifierTypeEnum = 3
	ProductIdentifierTypeEnumOEM ProductIdentifierTypeEnum = 4
)



type ReplacementProduct struct {
	ProductIdentifierType ProductIdentifierTypeEnum // Tag 0
	ProductIdentifierValue string // Tag 1
}

func (s *ReplacementProduct) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ProductIdentifierType Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.ProductIdentifierType)
    
	// Field: ProductIdentifierValue Tag: 1
    
        st[tlv.ContextTag(1)] = (s.ProductIdentifierValue)
    
	return st
}

func (s *ReplacementProduct) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := ProductIdentifierTypeEnum(v)
s.ProductIdentifierType = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(string); ok {
s.ProductIdentifierValue = v
}
        
        
	}

    return nil
}

