// Code generated by data_gen.go. DO NOT EDIT.

package dlog

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type IntentEnum uint8

const (
	IntentEnumEndUserSupport IntentEnum = 0
	IntentEnumNetworkDiag IntentEnum = 1
	IntentEnumCrashLogs IntentEnum = 2
)

type StatusEnum uint8

const (
	StatusEnumSuccess StatusEnum = 0
	StatusEnumExhausted StatusEnum = 1
	StatusEnumNoLogs StatusEnum = 2
	StatusEnumBusy StatusEnum = 3
	StatusEnumDenied StatusEnum = 4
)

type TransferProtocolEnum uint8

const (
	TransferProtocolEnumResponsePayload TransferProtocolEnum = 0
	TransferProtocolEnumBDX TransferProtocolEnum = 1
)



