// Code generated by data_gen.go. DO NOT EDIT.

package s

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type CopyModeBitmap uint8

const (
	CopyModeBitmapCopyAllScenes CopyModeBitmap = 0x1
)



type AttributeValuePair struct {
	AttributeID dm.AttributeID // Tag 0
	ValueUnsigned8 *uint8 // Tag 1
	ValueSigned8 *int8 // Tag 2
	ValueUnsigned16 *uint16 // Tag 3
	ValueSigned16 *int16 // Tag 4
	ValueUnsigned32 *uint32 // Tag 5
	ValueSigned32 *int32 // Tag 6
	ValueUnsigned64 *uint64 // Tag 7
	ValueSigned64 *int64 // Tag 8
}

func (s *AttributeValuePair) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: AttributeID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.AttributeID)
    
	// Field: ValueUnsigned8 Tag: 1
    if s.ValueUnsigned8 != nil {
        st[tlv.ContextTag(1)] = uint64(*s.ValueUnsigned8)
    }
	// Field: ValueSigned8 Tag: 2
    if s.ValueSigned8 != nil {
        st[tlv.ContextTag(2)] = int64(*s.ValueSigned8)
    }
	// Field: ValueUnsigned16 Tag: 3
    if s.ValueUnsigned16 != nil {
        st[tlv.ContextTag(3)] = uint64(*s.ValueUnsigned16)
    }
	// Field: ValueSigned16 Tag: 4
    if s.ValueSigned16 != nil {
        st[tlv.ContextTag(4)] = int64(*s.ValueSigned16)
    }
	// Field: ValueUnsigned32 Tag: 5
    if s.ValueUnsigned32 != nil {
        st[tlv.ContextTag(5)] = uint64(*s.ValueUnsigned32)
    }
	// Field: ValueSigned32 Tag: 6
    if s.ValueSigned32 != nil {
        st[tlv.ContextTag(6)] = int64(*s.ValueSigned32)
    }
	// Field: ValueUnsigned64 Tag: 7
    if s.ValueUnsigned64 != nil {
        st[tlv.ContextTag(7)] = uint64(*s.ValueUnsigned64)
    }
	// Field: ValueSigned64 Tag: 8
    if s.ValueSigned64 != nil {
        st[tlv.ContextTag(8)] = int64(*s.ValueSigned64)
    }
	return st
}

func (s *AttributeValuePair) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.AttributeID(v)
s.AttributeID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.ValueUnsigned8 = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int8(v)
s.ValueSigned8 = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.ValueUnsigned16 = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int16(v)
s.ValueSigned16 = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(5)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint32(v)
s.ValueUnsigned32 = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(6)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int32(v)
s.ValueSigned32 = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(7)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint64(v)
s.ValueUnsigned64 = &casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(8)]; ok {
        
        
            if v, ok := val.(int64); ok {
casted := int64(v)
s.ValueSigned64 = &casted
}
        
        
	}

    return nil
}

type ExtensionFieldSet struct {
	ClusterID dm.ClusterID // Tag 0
	AttributeValueList []AttributeValuePair // Tag 1
}

func (s *ExtensionFieldSet) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: ClusterID Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.ClusterID)
    
	// Field: AttributeValueList Tag: 1
    if len(s.AttributeValueList) > 0 {
        
        list := make(tlv.StructArray, 0, len(s.AttributeValueList))
        for _, v := range s.AttributeValueList {
            list = append(list, v.Encode())
        }
        st[tlv.ContextTag(1)] = list
        
    }
	return st
}

func (s *ExtensionFieldSet) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.ClusterID(v)
s.ClusterID = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
            
            if list, ok := val.(tlv.StructArray); ok {
                 for _, item := range list {
                    var newItem AttributeValuePair
                    if err := newItem.Decode(item); err != nil { return err }
                    s.AttributeValueList = append(s.AttributeValueList, newItem)
                 }
            }
            
        
	}

    return nil
}

type SceneInfo struct {
	SceneCount uint8 // Tag 0
	CurrentScene uint8 // Tag 1
	CurrentGroup dm.GroupID // Tag 2
	SceneValid bool // Tag 3
	RemainingCapacity uint8 // Tag 4
}

func (s *SceneInfo) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: SceneCount Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.SceneCount)
    
	// Field: CurrentScene Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.CurrentScene)
    
	// Field: CurrentGroup Tag: 2
    
        st[tlv.ContextTag(2)] = uint64(s.CurrentGroup)
    
	// Field: SceneValid Tag: 3
    
        st[tlv.ContextTag(3)] = (s.SceneValid)
    
	// Field: RemainingCapacity Tag: 4
    
        st[tlv.ContextTag(4)] = uint64(s.RemainingCapacity)
    
	return st
}

func (s *SceneInfo) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.SceneCount = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.CurrentScene = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(2)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.GroupID(v)
s.CurrentGroup = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(3)]; ok {
        
        
            if v, ok := val.(bool); ok {
s.SceneValid = v
}
        
        
	}
	if val, ok := st[tlv.ContextTag(4)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint8(v)
s.RemainingCapacity = casted
}
        
        
	}

    return nil
}

