// Code generated by data_gen.go. DO NOT EDIT.

package desc

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()







type DeviceType struct {
	DeviceType dm.DeviceTypeID // Tag 0
	Revision uint16 // Tag 1
}

func (s *DeviceType) Encode() tlv.Struct {
	st := make(tlv.Struct)
	// Field: DeviceType Tag: 0
    
        st[tlv.ContextTag(0)] = uint64(s.DeviceType)
    
	// Field: Revision Tag: 1
    
        st[tlv.ContextTag(1)] = uint64(s.Revision)
    
	return st
}

func (s *DeviceType) Decode(val any) error {
	st, ok := val.(tlv.Struct)
	if !ok {
		return fmt.Errorf("expected tlv.Struct, got %T", val)
	}
	if val, ok := st[tlv.ContextTag(0)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := dm.DeviceTypeID(v)
s.DeviceType = casted
}
        
        
	}
	if val, ok := st[tlv.ContextTag(1)]; ok {
        
        
            if v, ok := val.(uint64); ok {
casted := uint16(v)
s.Revision = casted
}
        
        
	}

    return nil
}

