// Code generated by data_gen.go. DO NOT EDIT.

package cadmin

import (
	"fmt"

	"github.com/etnz/matter/tlv"
	"github.com/etnz/matter/dm"
	
)

var _ = dm.SubjectID(0)
var _ = tlv.Struct{}
var _ = fmt.Sprint()





type CommissioningWindowStatusEnum uint8

const (
	CommissioningWindowStatusEnumWindowNotOpen CommissioningWindowStatusEnum = 0
	CommissioningWindowStatusEnumEnhancedWindowOpen CommissioningWindowStatusEnum = 1
	CommissioningWindowStatusEnumBasicWindowOpen CommissioningWindowStatusEnum = 2
)

type StatusCodeEnum uint8

const (
	StatusCodeEnumBusy StatusCodeEnum = 0x02
	StatusCodeEnumPAKEParameterError StatusCodeEnum = 0x03
	StatusCodeEnumWindowNotOpen StatusCodeEnum = 0x04
)



